/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */

export type GetIncidentsStatsParams = {
  /**
   * Start time (RFC3339 format)
   */
  started_at: string;
  /**
   * End time (RFC3339 format)
   */
  resolved_at: string;
};
