/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */

export type GetServicesIdIncidentsParams = {
  /**
   * Filter by incident ID
   */
  incident_id?: string;
  /**
   * Filter by resolved status
   */
  resolved?: boolean;
  /**
   * Page number (for pagination)
   */
  page?: number;
  /**
   * Number of items per page (default 20)
   */
  page_size?: number;
};
