/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */

export type GetSettingsNotificationsHistoryParams = {
  /**
   * Filter by status (e.g., 'sent', 'failed')
   */
  status?: string;
  /**
   * Order by field (default is 'created_at')
   */
  order_by?: string;
  /**
   * Page number for pagination (default is 1)
   */
  page?: number;
  /**
   * Number of items per page (default is 20)
   */
  page_size?: number;
};
