/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */

export type GetServicesIdStatsParams = {
  /**
   * Number of days (default 30)
   */
  days?: number;
};
