/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */

export type ModelsServiceStatus =
  (typeof ModelsServiceStatus)[keyof typeof ModelsServiceStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsServiceStatus = {
  StatusUnknown: "unknown",
  StatusUp: "up",
  StatusDown: "down",
  StatusMaintenance: "maintenance",
} as const;
