/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { MonitorsGRPCConfigCheckType } from './monitorsGRPCConfigCheckType';

export interface MonitorsGRPCConfig {
  check_type: MonitorsGRPCConfigCheckType;
  endpoint: string;
  insecure_tls?: boolean;
  service_name?: string;
  tls?: boolean;
}
