/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */

export type MonitorsEndpointConfigMethod = typeof MonitorsEndpointConfigMethod[keyof typeof MonitorsEndpointConfigMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MonitorsEndpointConfigMethod = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  HEAD: 'HEAD',
  OPTIONS: 'OPTIONS',
} as const;
