/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */

export type StorageServiceProtocolType = typeof StorageServiceProtocolType[keyof typeof StorageServiceProtocolType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageServiceProtocolType = {
  ServiceProtocolTypeHTTP: 'http',
  ServiceProtocolTypeTCP: 'tcp',
  ServiceProtocolTypeGRPC: 'grpc',
} as const;
