/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */

export interface StorageIncident {
  duration?: number;
  end_time?: string;
  error?: string;
  id?: string;
  resolved?: boolean;
  service_id?: string;
  start_time?: string;
}
