/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { StorageIncident } from "./storageIncident";

export interface StorecmnFindResponseWithCountStorageIncident {
  count?: number;
  items?: StorageIncident[];
}
