/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { WebAgentDTO } from "./webAgentDTO";

export interface StorecmnFindResponseWithCountWebAgentDTO {
  count?: number;
  items?: WebAgentDTO[];
}
