/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { WebAgentUpdateParamsConfig } from "./webAgentUpdateParamsConfig";

export interface WebAgentUpdateParams {
  config?: WebAgentUpdateParamsConfig;
  description?: string;
  isEnabled?: boolean;
  name?: string;
  tags?: string[];
}
