/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { MonitorsConfig } from "./monitorsConfig";
import type { StorageServiceProtocolType } from "./storageServiceProtocolType";

export interface WebCreateUpdateServiceRequest {
  config?: MonitorsConfig;
  interval?: number;
  is_enabled?: boolean;
  name?: string;
  protocol?: StorageServiceProtocolType;
  retries?: number;
  tags?: string[];
  timeout?: number;
}
