/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { MonitorsConfig } from "./monitorsConfig";
import type { ModelsServiceProtocolType } from "./modelsServiceProtocolType";

export interface WebCreateUpdateServiceRequest {
  config?: MonitorsConfig;
  interval?: number;
  is_enabled?: boolean;
  name?: string;
  protocol?: ModelsServiceProtocolType;
  retries?: number;
  tags?: string[];
  timeout?: number;
}
