/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */

/**
 * Successful response
 */
export interface WebSuccessResponse {
  message?: string;
}
