/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { MonitorsConfig } from "./monitorsConfig";
import type { ModelsServiceProtocolType } from "./modelsServiceProtocolType";
import type { ModelsServiceStatus } from "./modelsServiceStatus";

export interface WebServiceDTO {
  active_incidents?: number;
  config?: MonitorsConfig;
  consecutive_fails?: number;
  consecutive_success?: number;
  id?: string;
  interval?: number;
  is_enabled?: boolean;
  last_check?: string;
  last_error?: string;
  name?: string;
  next_check?: string;
  protocol?: ModelsServiceProtocolType;
  response_time?: number;
  retries?: number;
  status?: ModelsServiceStatus;
  tags?: string[];
  timeout?: number;
  total_checks?: number;
  total_incidents?: number;
}
