/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { WebAvailableUpdate } from "./webAvailableUpdate";

export interface WebServerInfoResponse {
  arch?: string;
  available_update?: WebAvailableUpdate;
  build_date?: string;
  commit_hash?: string;
  go_version?: string;
  os?: string;
  version?: string;
}
