/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { ModelsAvailableUpdate } from "./modelsAvailableUpdate";

export interface WebServerInfoResponse {
  arch?: string;
  available_update?: ModelsAvailableUpdate;
  build_date?: string;
  commit_hash?: string;
  go_version?: string;
  os?: string;
  sqlite_version?: string;
  version?: string;
}
