// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sentinel/agents/v1/agents.proto

package agentsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/agents/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentsServiceName is the fully-qualified name of the AgentsService service.
	AgentsServiceName = "sentinel.agents.v1.AgentsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentsServiceAgentsListProcedure is the fully-qualified name of the AgentsService's AgentsList
	// RPC.
	AgentsServiceAgentsListProcedure = "/sentinel.agents.v1.AgentsService/AgentsList"
	// AgentsServiceAgentsGetProcedure is the fully-qualified name of the AgentsService's AgentsGet RPC.
	AgentsServiceAgentsGetProcedure = "/sentinel.agents.v1.AgentsService/AgentsGet"
	// AgentsServiceAgentsCreateProcedure is the fully-qualified name of the AgentsService's
	// AgentsCreate RPC.
	AgentsServiceAgentsCreateProcedure = "/sentinel.agents.v1.AgentsService/AgentsCreate"
	// AgentsServiceAgentsUpdateProcedure is the fully-qualified name of the AgentsService's
	// AgentsUpdate RPC.
	AgentsServiceAgentsUpdateProcedure = "/sentinel.agents.v1.AgentsService/AgentsUpdate"
	// AgentsServiceAgentsDeleteProcedure is the fully-qualified name of the AgentsService's
	// AgentsDelete RPC.
	AgentsServiceAgentsDeleteProcedure = "/sentinel.agents.v1.AgentsService/AgentsDelete"
	// AgentsServiceAgentsSubscribeProcedure is the fully-qualified name of the AgentsService's
	// AgentsSubscribe RPC.
	AgentsServiceAgentsSubscribeProcedure = "/sentinel.agents.v1.AgentsService/AgentsSubscribe"
)

// AgentsServiceClient is a client for the sentinel.agents.v1.AgentsService service.
type AgentsServiceClient interface {
	AgentsList(context.Context, *connect.Request[v1.AgentsListRequest]) (*connect.Response[v1.AgentsListResponse], error)
	AgentsGet(context.Context, *connect.Request[v1.AgentsGetRequest]) (*connect.Response[v1.AgentsGetResponse], error)
	AgentsCreate(context.Context, *connect.Request[v1.AgentsCreateRequest]) (*connect.Response[v1.AgentsCreateResponse], error)
	AgentsUpdate(context.Context, *connect.Request[v1.AgentsUpdateRequest]) (*connect.Response[v1.AgentsUpdateResponse], error)
	AgentsDelete(context.Context, *connect.Request[v1.AgentsDeleteRequest]) (*connect.Response[v1.AgentsDeleteResponse], error)
	AgentsSubscribe(context.Context, *connect.Request[v1.AgentsSubscribeRequest]) (*connect.ServerStreamForClient[v1.AgentsSubscribeResponse], error)
}

// NewAgentsServiceClient constructs a client for the sentinel.agents.v1.AgentsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentsServiceMethods := v1.File_sentinel_agents_v1_agents_proto.Services().ByName("AgentsService").Methods()
	return &agentsServiceClient{
		agentsList: connect.NewClient[v1.AgentsListRequest, v1.AgentsListResponse](
			httpClient,
			baseURL+AgentsServiceAgentsListProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("AgentsList")),
			connect.WithClientOptions(opts...),
		),
		agentsGet: connect.NewClient[v1.AgentsGetRequest, v1.AgentsGetResponse](
			httpClient,
			baseURL+AgentsServiceAgentsGetProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("AgentsGet")),
			connect.WithClientOptions(opts...),
		),
		agentsCreate: connect.NewClient[v1.AgentsCreateRequest, v1.AgentsCreateResponse](
			httpClient,
			baseURL+AgentsServiceAgentsCreateProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("AgentsCreate")),
			connect.WithClientOptions(opts...),
		),
		agentsUpdate: connect.NewClient[v1.AgentsUpdateRequest, v1.AgentsUpdateResponse](
			httpClient,
			baseURL+AgentsServiceAgentsUpdateProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("AgentsUpdate")),
			connect.WithClientOptions(opts...),
		),
		agentsDelete: connect.NewClient[v1.AgentsDeleteRequest, v1.AgentsDeleteResponse](
			httpClient,
			baseURL+AgentsServiceAgentsDeleteProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("AgentsDelete")),
			connect.WithClientOptions(opts...),
		),
		agentsSubscribe: connect.NewClient[v1.AgentsSubscribeRequest, v1.AgentsSubscribeResponse](
			httpClient,
			baseURL+AgentsServiceAgentsSubscribeProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("AgentsSubscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentsServiceClient implements AgentsServiceClient.
type agentsServiceClient struct {
	agentsList      *connect.Client[v1.AgentsListRequest, v1.AgentsListResponse]
	agentsGet       *connect.Client[v1.AgentsGetRequest, v1.AgentsGetResponse]
	agentsCreate    *connect.Client[v1.AgentsCreateRequest, v1.AgentsCreateResponse]
	agentsUpdate    *connect.Client[v1.AgentsUpdateRequest, v1.AgentsUpdateResponse]
	agentsDelete    *connect.Client[v1.AgentsDeleteRequest, v1.AgentsDeleteResponse]
	agentsSubscribe *connect.Client[v1.AgentsSubscribeRequest, v1.AgentsSubscribeResponse]
}

// AgentsList calls sentinel.agents.v1.AgentsService.AgentsList.
func (c *agentsServiceClient) AgentsList(ctx context.Context, req *connect.Request[v1.AgentsListRequest]) (*connect.Response[v1.AgentsListResponse], error) {
	return c.agentsList.CallUnary(ctx, req)
}

// AgentsGet calls sentinel.agents.v1.AgentsService.AgentsGet.
func (c *agentsServiceClient) AgentsGet(ctx context.Context, req *connect.Request[v1.AgentsGetRequest]) (*connect.Response[v1.AgentsGetResponse], error) {
	return c.agentsGet.CallUnary(ctx, req)
}

// AgentsCreate calls sentinel.agents.v1.AgentsService.AgentsCreate.
func (c *agentsServiceClient) AgentsCreate(ctx context.Context, req *connect.Request[v1.AgentsCreateRequest]) (*connect.Response[v1.AgentsCreateResponse], error) {
	return c.agentsCreate.CallUnary(ctx, req)
}

// AgentsUpdate calls sentinel.agents.v1.AgentsService.AgentsUpdate.
func (c *agentsServiceClient) AgentsUpdate(ctx context.Context, req *connect.Request[v1.AgentsUpdateRequest]) (*connect.Response[v1.AgentsUpdateResponse], error) {
	return c.agentsUpdate.CallUnary(ctx, req)
}

// AgentsDelete calls sentinel.agents.v1.AgentsService.AgentsDelete.
func (c *agentsServiceClient) AgentsDelete(ctx context.Context, req *connect.Request[v1.AgentsDeleteRequest]) (*connect.Response[v1.AgentsDeleteResponse], error) {
	return c.agentsDelete.CallUnary(ctx, req)
}

// AgentsSubscribe calls sentinel.agents.v1.AgentsService.AgentsSubscribe.
func (c *agentsServiceClient) AgentsSubscribe(ctx context.Context, req *connect.Request[v1.AgentsSubscribeRequest]) (*connect.ServerStreamForClient[v1.AgentsSubscribeResponse], error) {
	return c.agentsSubscribe.CallServerStream(ctx, req)
}

// AgentsServiceHandler is an implementation of the sentinel.agents.v1.AgentsService service.
type AgentsServiceHandler interface {
	AgentsList(context.Context, *connect.Request[v1.AgentsListRequest]) (*connect.Response[v1.AgentsListResponse], error)
	AgentsGet(context.Context, *connect.Request[v1.AgentsGetRequest]) (*connect.Response[v1.AgentsGetResponse], error)
	AgentsCreate(context.Context, *connect.Request[v1.AgentsCreateRequest]) (*connect.Response[v1.AgentsCreateResponse], error)
	AgentsUpdate(context.Context, *connect.Request[v1.AgentsUpdateRequest]) (*connect.Response[v1.AgentsUpdateResponse], error)
	AgentsDelete(context.Context, *connect.Request[v1.AgentsDeleteRequest]) (*connect.Response[v1.AgentsDeleteResponse], error)
	AgentsSubscribe(context.Context, *connect.Request[v1.AgentsSubscribeRequest], *connect.ServerStream[v1.AgentsSubscribeResponse]) error
}

// NewAgentsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentsServiceHandler(svc AgentsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentsServiceMethods := v1.File_sentinel_agents_v1_agents_proto.Services().ByName("AgentsService").Methods()
	agentsServiceAgentsListHandler := connect.NewUnaryHandler(
		AgentsServiceAgentsListProcedure,
		svc.AgentsList,
		connect.WithSchema(agentsServiceMethods.ByName("AgentsList")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceAgentsGetHandler := connect.NewUnaryHandler(
		AgentsServiceAgentsGetProcedure,
		svc.AgentsGet,
		connect.WithSchema(agentsServiceMethods.ByName("AgentsGet")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceAgentsCreateHandler := connect.NewUnaryHandler(
		AgentsServiceAgentsCreateProcedure,
		svc.AgentsCreate,
		connect.WithSchema(agentsServiceMethods.ByName("AgentsCreate")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceAgentsUpdateHandler := connect.NewUnaryHandler(
		AgentsServiceAgentsUpdateProcedure,
		svc.AgentsUpdate,
		connect.WithSchema(agentsServiceMethods.ByName("AgentsUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceAgentsDeleteHandler := connect.NewUnaryHandler(
		AgentsServiceAgentsDeleteProcedure,
		svc.AgentsDelete,
		connect.WithSchema(agentsServiceMethods.ByName("AgentsDelete")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceAgentsSubscribeHandler := connect.NewServerStreamHandler(
		AgentsServiceAgentsSubscribeProcedure,
		svc.AgentsSubscribe,
		connect.WithSchema(agentsServiceMethods.ByName("AgentsSubscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sentinel.agents.v1.AgentsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentsServiceAgentsListProcedure:
			agentsServiceAgentsListHandler.ServeHTTP(w, r)
		case AgentsServiceAgentsGetProcedure:
			agentsServiceAgentsGetHandler.ServeHTTP(w, r)
		case AgentsServiceAgentsCreateProcedure:
			agentsServiceAgentsCreateHandler.ServeHTTP(w, r)
		case AgentsServiceAgentsUpdateProcedure:
			agentsServiceAgentsUpdateHandler.ServeHTTP(w, r)
		case AgentsServiceAgentsDeleteProcedure:
			agentsServiceAgentsDeleteHandler.ServeHTTP(w, r)
		case AgentsServiceAgentsSubscribeProcedure:
			agentsServiceAgentsSubscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentsServiceHandler struct{}

func (UnimplementedAgentsServiceHandler) AgentsList(context.Context, *connect.Request[v1.AgentsListRequest]) (*connect.Response[v1.AgentsListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.agents.v1.AgentsService.AgentsList is not implemented"))
}

func (UnimplementedAgentsServiceHandler) AgentsGet(context.Context, *connect.Request[v1.AgentsGetRequest]) (*connect.Response[v1.AgentsGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.agents.v1.AgentsService.AgentsGet is not implemented"))
}

func (UnimplementedAgentsServiceHandler) AgentsCreate(context.Context, *connect.Request[v1.AgentsCreateRequest]) (*connect.Response[v1.AgentsCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.agents.v1.AgentsService.AgentsCreate is not implemented"))
}

func (UnimplementedAgentsServiceHandler) AgentsUpdate(context.Context, *connect.Request[v1.AgentsUpdateRequest]) (*connect.Response[v1.AgentsUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.agents.v1.AgentsService.AgentsUpdate is not implemented"))
}

func (UnimplementedAgentsServiceHandler) AgentsDelete(context.Context, *connect.Request[v1.AgentsDeleteRequest]) (*connect.Response[v1.AgentsDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.agents.v1.AgentsService.AgentsDelete is not implemented"))
}

func (UnimplementedAgentsServiceHandler) AgentsSubscribe(context.Context, *connect.Request[v1.AgentsSubscribeRequest], *connect.ServerStream[v1.AgentsSubscribeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.agents.v1.AgentsService.AgentsSubscribe is not implemented"))
}
