// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources_gen.sql

package repo_resources

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
	"github.com/sxwebdev/sentinel/internal/store/storecmn"
)

const create = `-- name: Create :one
INSERT INTO resources (id, project_id, name, description, tags, payload)
	VALUES (?, ?, ?, ?, ?, ?)
	RETURNING id, project_id, name, description, tags, payload, created_at, updated_at
`

type CreateParams struct {
	ID          string             `db:"id" json:"id"`
	ProjectID   string             `db:"project_id" json:"project_id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	Tags        storecmn.JSONField `db:"tags" json:"tags"`
	Payload     storecmn.JSONField `db:"payload" json:"payload"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Resource, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.Payload,
	)
	var i models.Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM resources WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, project_id, name, description, tags, payload, created_at, updated_at FROM resources WHERE project_id=?
`

func (q *Queries) GetAll(ctx context.Context, projectID string) ([]*models.Resource, error) {
	rows, err := q.db.QueryContext(ctx, getAll, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Resource{}
	for rows.Next() {
		var i models.Resource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, project_id, name, description, tags, payload, created_at, updated_at FROM resources WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Resource, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
