// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.12
package repo_maintenance_windows

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameMaintenanceWindows TableName = "maintenance_windows"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameMaintenanceWindowsId        ColumnName = "id"
	ColumnNameMaintenanceWindowsName      ColumnName = "name"
	ColumnNameMaintenanceWindowsStartAt   ColumnName = "start_at"
	ColumnNameMaintenanceWindowsEndAt     ColumnName = "end_at"
	ColumnNameMaintenanceWindowsReason    ColumnName = "reason"
	ColumnNameMaintenanceWindowsCreatedAt ColumnName = "created_at"
	ColumnNameMaintenanceWindowsUpdatedAt ColumnName = "updated_at"
)

func MaintenanceWindowsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameMaintenanceWindowsId,
		ColumnNameMaintenanceWindowsName,
		ColumnNameMaintenanceWindowsStartAt,
		ColumnNameMaintenanceWindowsEndAt,
		ColumnNameMaintenanceWindowsReason,
		ColumnNameMaintenanceWindowsCreatedAt,
		ColumnNameMaintenanceWindowsUpdatedAt,
	}
}
