// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance_windows_gen.sql

package repo_maintenance_windows

import (
	"context"
	"time"

	"github.com/sxwebdev/sentinel/internal/models"
)

const create = `-- name: Create :one
INSERT INTO maintenance_windows (id, name, start_at, end_at, reason)
	VALUES (?, ?, ?, ?, ?)
	RETURNING id, name, start_at, end_at, reason, created_at, updated_at
`

type CreateParams struct {
	ID      string    `db:"id" json:"id"`
	Name    string    `db:"name" json:"name"`
	StartAt time.Time `db:"start_at" json:"start_at"`
	EndAt   time.Time `db:"end_at" json:"end_at"`
	Reason  *string   `db:"reason" json:"reason"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.MaintenanceWindow, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Name,
		arg.StartAt,
		arg.EndAt,
		arg.Reason,
	)
	var i models.MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartAt,
		&i.EndAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM maintenance_windows WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, name, start_at, end_at, reason, created_at, updated_at FROM maintenance_windows
`

func (q *Queries) GetAll(ctx context.Context) ([]*models.MaintenanceWindow, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.MaintenanceWindow{}
	for rows.Next() {
		var i models.MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartAt,
			&i.EndAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, name, start_at, end_at, reason, created_at, updated_at FROM maintenance_windows WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.MaintenanceWindow, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartAt,
		&i.EndAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
