// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_maintenance_windows

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.MaintenanceWindow, error)
	Delete(ctx context.Context, id string) error
	GetAll(ctx context.Context) ([]*models.MaintenanceWindow, error)
	GetByID(ctx context.Context, id string) (*models.MaintenanceWindow, error)
}

var _ Querier = (*Queries)(nil)
