// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents_gen.sql

package repo_agents

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
	"github.com/sxwebdev/sentinel/internal/store/storecmn"
)

const create = `-- name: Create :one
INSERT INTO agents (id, name, description, secret_hash, token_hint, kind, location, tags, config, project_id)
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	RETURNING id, name, description, secret_hash, token_hint, fingerprint, kind, status, is_enabled, location, tags, config, system_info, project_id, last_seen_at, created_at, updated_at
`

type CreateParams struct {
	ID          string             `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	SecretHash  string             `db:"secret_hash" json:"secret_hash"`
	TokenHint   string             `db:"token_hint" json:"token_hint"`
	Kind        string             `db:"kind" json:"kind"`
	Location    *string            `db:"location" json:"location"`
	Tags        storecmn.JSONField `db:"tags" json:"tags"`
	Config      storecmn.JSONField `db:"config" json:"config"`
	ProjectID   string             `db:"project_id" json:"project_id"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Agent, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SecretHash,
		arg.TokenHint,
		arg.Kind,
		arg.Location,
		arg.Tags,
		arg.Config,
		arg.ProjectID,
	)
	var i models.Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SecretHash,
		&i.TokenHint,
		&i.Fingerprint,
		&i.Kind,
		&i.Status,
		&i.IsEnabled,
		&i.Location,
		&i.Tags,
		&i.Config,
		&i.SystemInfo,
		&i.ProjectID,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM agents WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, name, description, secret_hash, token_hint, fingerprint, kind, status, is_enabled, location, tags, config, system_info, project_id, last_seen_at, created_at, updated_at FROM agents WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Agent, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SecretHash,
		&i.TokenHint,
		&i.Fingerprint,
		&i.Kind,
		&i.Status,
		&i.IsEnabled,
		&i.Location,
		&i.Tags,
		&i.Config,
		&i.SystemInfo,
		&i.ProjectID,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
