// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents_gen.sql

package repo_agents

import (
	"context"
	"time"

	"github.com/sxwebdev/sentinel/internal/models"
	"github.com/sxwebdev/sentinel/internal/store/storecmn"
)

const create = `-- name: Create :one
INSERT INTO agents (id, name, description, secret_hash, token_hint, last_assignment_rev, tags, config, last_connected_at)
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	RETURNING id, name, description, secret_hash, token_hint, fingerprint, last_assignment_rev, status, is_enabled, json(tags), json(config), json(system_info), last_connected_at, created_at, updated_at
`

type CreateParams struct {
	ID                string             `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Description       *string            `db:"description" json:"description"`
	SecretHash        string             `db:"secret_hash" json:"secret_hash"`
	TokenHint         string             `db:"token_hint" json:"token_hint"`
	LastAssignmentRev *string            `db:"last_assignment_rev" json:"last_assignment_rev"`
	Tags              storecmn.JSONField `db:"tags" json:"tags"`
	Config            storecmn.JSONField `db:"config" json:"config"`
	LastConnectedAt   *time.Time         `db:"last_connected_at" json:"last_connected_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Agent, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SecretHash,
		arg.TokenHint,
		arg.LastAssignmentRev,
		arg.Tags,
		arg.Config,
		arg.LastConnectedAt,
	)
	var i models.Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SecretHash,
		&i.TokenHint,
		&i.Fingerprint,
		&i.LastAssignmentRev,
		&i.Status,
		&i.IsEnabled,
		&i.Tags,
		&i.Config,
		&i.SystemInfo,
		&i.LastConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM agents WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, name, description, secret_hash, token_hint, fingerprint, last_assignment_rev, status, is_enabled, json(tags), json(config), json(system_info), last_connected_at, created_at, updated_at FROM agents WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Agent, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SecretHash,
		&i.TokenHint,
		&i.Fingerprint,
		&i.LastAssignmentRev,
		&i.Status,
		&i.IsEnabled,
		&i.Tags,
		&i.Config,
		&i.SystemInfo,
		&i.LastConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
