// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package repo_agents

import (
	"context"
)

const exist = `-- name: Exist :one
SELECT EXISTS (SELECT 1 FROM agents WHERE id=? LIMIT 1)
`

func (q *Queries) Exist(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, exist, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
