// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.11
package repo_agents

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameAgents TableName = "agents"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameAgentsId                ColumnName = "id"
	ColumnNameAgentsName              ColumnName = "name"
	ColumnNameAgentsDescription       ColumnName = "description"
	ColumnNameAgentsSecretHash        ColumnName = "secret_hash"
	ColumnNameAgentsTokenHint         ColumnName = "token_hint"
	ColumnNameAgentsFingerprint       ColumnName = "fingerprint"
	ColumnNameAgentsLastAssignmentRev ColumnName = "last_assignment_rev"
	ColumnNameAgentsStatus            ColumnName = "status"
	ColumnNameAgentsIsEnabled         ColumnName = "is_enabled"
	ColumnNameAgentsTags              ColumnName = "tags"
	ColumnNameAgentsConfig            ColumnName = "config"
	ColumnNameAgentsSystemInfo        ColumnName = "system_info"
	ColumnNameAgentsLastOnlineAt      ColumnName = "last_online_at"
	ColumnNameAgentsCreatedAt         ColumnName = "created_at"
	ColumnNameAgentsUpdatedAt         ColumnName = "updated_at"
)

func AgentsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameAgentsId,
		ColumnNameAgentsName,
		ColumnNameAgentsDescription,
		ColumnNameAgentsSecretHash,
		ColumnNameAgentsTokenHint,
		ColumnNameAgentsFingerprint,
		ColumnNameAgentsLastAssignmentRev,
		ColumnNameAgentsStatus,
		ColumnNameAgentsIsEnabled,
		ColumnNameAgentsTags,
		ColumnNameAgentsConfig,
		ColumnNameAgentsSystemInfo,
		ColumnNameAgentsLastOnlineAt,
		ColumnNameAgentsCreatedAt,
		ColumnNameAgentsUpdatedAt,
	}
}
