/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type {
  GetServicesIdStatsParams,
  StorageServiceStats,
} from "../../types/model";

import { customFetcher } from ".././baseApi";

export const getStatistics = () => {
  /**
   * Returns service statistics for the specified period
   * @summary Get service statistics
   */
  const getServicesIdStats = (
    id: string,
    params?: GetServicesIdStatsParams,
  ) => {
    return customFetcher<StorageServiceStats>({
      url: `/services/${id}/stats`,
      method: "GET",
      params,
    });
  };
  return { getServicesIdStats };
};
export type GetServicesIdStatsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStatistics>["getServicesIdStats"]>>
>;
