// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sentinel/system/v1/service.proto

package systemv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/system/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SystemServiceName is the fully-qualified name of the SystemService service.
	SystemServiceName = "sentinel.system.v1.SystemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SystemServiceCheckIsInitializedProcedure is the fully-qualified name of the SystemService's
	// CheckIsInitialized RPC.
	SystemServiceCheckIsInitializedProcedure = "/sentinel.system.v1.SystemService/CheckIsInitialized"
	// SystemServiceInitializeProcedure is the fully-qualified name of the SystemService's Initialize
	// RPC.
	SystemServiceInitializeProcedure = "/sentinel.system.v1.SystemService/Initialize"
	// SystemServiceGetSystemInfoProcedure is the fully-qualified name of the SystemService's
	// GetSystemInfo RPC.
	SystemServiceGetSystemInfoProcedure = "/sentinel.system.v1.SystemService/GetSystemInfo"
	// SystemServiceCheckForUpdatesProcedure is the fully-qualified name of the SystemService's
	// CheckForUpdates RPC.
	SystemServiceCheckForUpdatesProcedure = "/sentinel.system.v1.SystemService/CheckForUpdates"
)

// SystemServiceClient is a client for the sentinel.system.v1.SystemService service.
type SystemServiceClient interface {
	CheckIsInitialized(context.Context, *connect.Request[v1.CheckIsInitializedRequest]) (*connect.Response[v1.CheckIsInitializedResponse], error)
	Initialize(context.Context, *connect.Request[v1.InitializeRequest]) (*connect.Response[v1.InitializeResponse], error)
	GetSystemInfo(context.Context, *connect.Request[v1.GetSystemInfoRequest]) (*connect.Response[v1.GetSystemInfoResponse], error)
	CheckForUpdates(context.Context, *connect.Request[v1.CheckForUpdatesRequest]) (*connect.Response[v1.CheckForUpdatesResponse], error)
}

// NewSystemServiceClient constructs a client for the sentinel.system.v1.SystemService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSystemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SystemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	systemServiceMethods := v1.File_sentinel_system_v1_service_proto.Services().ByName("SystemService").Methods()
	return &systemServiceClient{
		checkIsInitialized: connect.NewClient[v1.CheckIsInitializedRequest, v1.CheckIsInitializedResponse](
			httpClient,
			baseURL+SystemServiceCheckIsInitializedProcedure,
			connect.WithSchema(systemServiceMethods.ByName("CheckIsInitialized")),
			connect.WithClientOptions(opts...),
		),
		initialize: connect.NewClient[v1.InitializeRequest, v1.InitializeResponse](
			httpClient,
			baseURL+SystemServiceInitializeProcedure,
			connect.WithSchema(systemServiceMethods.ByName("Initialize")),
			connect.WithClientOptions(opts...),
		),
		getSystemInfo: connect.NewClient[v1.GetSystemInfoRequest, v1.GetSystemInfoResponse](
			httpClient,
			baseURL+SystemServiceGetSystemInfoProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetSystemInfo")),
			connect.WithClientOptions(opts...),
		),
		checkForUpdates: connect.NewClient[v1.CheckForUpdatesRequest, v1.CheckForUpdatesResponse](
			httpClient,
			baseURL+SystemServiceCheckForUpdatesProcedure,
			connect.WithSchema(systemServiceMethods.ByName("CheckForUpdates")),
			connect.WithClientOptions(opts...),
		),
	}
}

// systemServiceClient implements SystemServiceClient.
type systemServiceClient struct {
	checkIsInitialized *connect.Client[v1.CheckIsInitializedRequest, v1.CheckIsInitializedResponse]
	initialize         *connect.Client[v1.InitializeRequest, v1.InitializeResponse]
	getSystemInfo      *connect.Client[v1.GetSystemInfoRequest, v1.GetSystemInfoResponse]
	checkForUpdates    *connect.Client[v1.CheckForUpdatesRequest, v1.CheckForUpdatesResponse]
}

// CheckIsInitialized calls sentinel.system.v1.SystemService.CheckIsInitialized.
func (c *systemServiceClient) CheckIsInitialized(ctx context.Context, req *connect.Request[v1.CheckIsInitializedRequest]) (*connect.Response[v1.CheckIsInitializedResponse], error) {
	return c.checkIsInitialized.CallUnary(ctx, req)
}

// Initialize calls sentinel.system.v1.SystemService.Initialize.
func (c *systemServiceClient) Initialize(ctx context.Context, req *connect.Request[v1.InitializeRequest]) (*connect.Response[v1.InitializeResponse], error) {
	return c.initialize.CallUnary(ctx, req)
}

// GetSystemInfo calls sentinel.system.v1.SystemService.GetSystemInfo.
func (c *systemServiceClient) GetSystemInfo(ctx context.Context, req *connect.Request[v1.GetSystemInfoRequest]) (*connect.Response[v1.GetSystemInfoResponse], error) {
	return c.getSystemInfo.CallUnary(ctx, req)
}

// CheckForUpdates calls sentinel.system.v1.SystemService.CheckForUpdates.
func (c *systemServiceClient) CheckForUpdates(ctx context.Context, req *connect.Request[v1.CheckForUpdatesRequest]) (*connect.Response[v1.CheckForUpdatesResponse], error) {
	return c.checkForUpdates.CallUnary(ctx, req)
}

// SystemServiceHandler is an implementation of the sentinel.system.v1.SystemService service.
type SystemServiceHandler interface {
	CheckIsInitialized(context.Context, *connect.Request[v1.CheckIsInitializedRequest]) (*connect.Response[v1.CheckIsInitializedResponse], error)
	Initialize(context.Context, *connect.Request[v1.InitializeRequest]) (*connect.Response[v1.InitializeResponse], error)
	GetSystemInfo(context.Context, *connect.Request[v1.GetSystemInfoRequest]) (*connect.Response[v1.GetSystemInfoResponse], error)
	CheckForUpdates(context.Context, *connect.Request[v1.CheckForUpdatesRequest]) (*connect.Response[v1.CheckForUpdatesResponse], error)
}

// NewSystemServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSystemServiceHandler(svc SystemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	systemServiceMethods := v1.File_sentinel_system_v1_service_proto.Services().ByName("SystemService").Methods()
	systemServiceCheckIsInitializedHandler := connect.NewUnaryHandler(
		SystemServiceCheckIsInitializedProcedure,
		svc.CheckIsInitialized,
		connect.WithSchema(systemServiceMethods.ByName("CheckIsInitialized")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceInitializeHandler := connect.NewUnaryHandler(
		SystemServiceInitializeProcedure,
		svc.Initialize,
		connect.WithSchema(systemServiceMethods.ByName("Initialize")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetSystemInfoHandler := connect.NewUnaryHandler(
		SystemServiceGetSystemInfoProcedure,
		svc.GetSystemInfo,
		connect.WithSchema(systemServiceMethods.ByName("GetSystemInfo")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceCheckForUpdatesHandler := connect.NewUnaryHandler(
		SystemServiceCheckForUpdatesProcedure,
		svc.CheckForUpdates,
		connect.WithSchema(systemServiceMethods.ByName("CheckForUpdates")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sentinel.system.v1.SystemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SystemServiceCheckIsInitializedProcedure:
			systemServiceCheckIsInitializedHandler.ServeHTTP(w, r)
		case SystemServiceInitializeProcedure:
			systemServiceInitializeHandler.ServeHTTP(w, r)
		case SystemServiceGetSystemInfoProcedure:
			systemServiceGetSystemInfoHandler.ServeHTTP(w, r)
		case SystemServiceCheckForUpdatesProcedure:
			systemServiceCheckForUpdatesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSystemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSystemServiceHandler struct{}

func (UnimplementedSystemServiceHandler) CheckIsInitialized(context.Context, *connect.Request[v1.CheckIsInitializedRequest]) (*connect.Response[v1.CheckIsInitializedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.system.v1.SystemService.CheckIsInitialized is not implemented"))
}

func (UnimplementedSystemServiceHandler) Initialize(context.Context, *connect.Request[v1.InitializeRequest]) (*connect.Response[v1.InitializeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.system.v1.SystemService.Initialize is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetSystemInfo(context.Context, *connect.Request[v1.GetSystemInfoRequest]) (*connect.Response[v1.GetSystemInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.system.v1.SystemService.GetSystemInfo is not implemented"))
}

func (UnimplementedSystemServiceHandler) CheckForUpdates(context.Context, *connect.Request[v1.CheckForUpdatesRequest]) (*connect.Response[v1.CheckForUpdatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.system.v1.SystemService.CheckForUpdates is not implemented"))
}
