log:
  format: ""
  level: ""
  console_colored: false
  trace: ""
  with_caller: false
  with_stack_trace: false
ops:
  enabled: false
  network: ""
  tracing_enabled: false
  metrics:
    enabled: false
    path: ""
    port: ""
    basic_auth:
      enabled: false
      username: ""
      password: ""
  healthy:
    enabled: false
    path: ""
    port: ""
  profiler:
    enabled: false
    path: ""
    port: ""
    write_timeout: 0
server:
  port: 8080
  host: 0.0.0.0
  base_host: localhost:8080
  frontend:
    base_url: http://localhost:8080/api/v1
    socket_url: ws://localhost:8080/ws
  auth:
    enabled: false
    users: []
monitoring:
  global:
    default_interval: 30s
    default_timeout: 10s
    default_retries: 3
database:
  path: ./data/db.sqlite
notifications:
  enabled: false
  urls: []
timezone: UTC
