services:
  sentinel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: local-dev
        COMMIT_HASH: local
        BUILD_DATE: local
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/data
      - ./config.yaml:/root/config.yaml
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/services",
        ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  sentinel-data:
    driver: local
