// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.11
package repo_notification_history

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameNotificationHistory TableName = "notification_history"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameNotificationHistoryId           ColumnName = "id"
	ColumnNameNotificationHistoryProviderId   ColumnName = "provider_id"
	ColumnNameNotificationHistoryIncidentId   ColumnName = "incident_id"
	ColumnNameNotificationHistoryMessage      ColumnName = "message"
	ColumnNameNotificationHistoryStatus       ColumnName = "status"
	ColumnNameNotificationHistoryErrorMessage ColumnName = "error_message"
	ColumnNameNotificationHistoryCreatedAt    ColumnName = "created_at"
)

func NotificationHistoryColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameNotificationHistoryId,
		ColumnNameNotificationHistoryProviderId,
		ColumnNameNotificationHistoryIncidentId,
		ColumnNameNotificationHistoryMessage,
		ColumnNameNotificationHistoryStatus,
		ColumnNameNotificationHistoryErrorMessage,
		ColumnNameNotificationHistoryCreatedAt,
	}
}
