// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.13
package repo_notification_history

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameNotificationHistory TableName = "notification_history"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameNotificationHistoryId            ColumnName = "id"
	ColumnNameNotificationHistoryAlertId       ColumnName = "alert_id"
	ColumnNameNotificationHistoryProviderId    ColumnName = "provider_id"
	ColumnNameNotificationHistoryMessage       ColumnName = "message"
	ColumnNameNotificationHistoryStatus        ColumnName = "status"
	ColumnNameNotificationHistoryResponse      ColumnName = "response"
	ColumnNameNotificationHistoryAttempts      ColumnName = "attempts"
	ColumnNameNotificationHistoryErrorMessage  ColumnName = "error_message"
	ColumnNameNotificationHistoryLastAttemptAt ColumnName = "last_attempt_at"
	ColumnNameNotificationHistorySentAt        ColumnName = "sent_at"
	ColumnNameNotificationHistoryCreatedAt     ColumnName = "created_at"
	ColumnNameNotificationHistoryUpdatedAt     ColumnName = "updated_at"
)

func NotificationHistoryColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameNotificationHistoryId,
		ColumnNameNotificationHistoryAlertId,
		ColumnNameNotificationHistoryProviderId,
		ColumnNameNotificationHistoryMessage,
		ColumnNameNotificationHistoryStatus,
		ColumnNameNotificationHistoryResponse,
		ColumnNameNotificationHistoryAttempts,
		ColumnNameNotificationHistoryErrorMessage,
		ColumnNameNotificationHistoryLastAttemptAt,
		ColumnNameNotificationHistorySentAt,
		ColumnNameNotificationHistoryCreatedAt,
		ColumnNameNotificationHistoryUpdatedAt,
	}
}
