// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_history_gen.sql

package repo_notification_history

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

const create = `-- name: Create :one
INSERT INTO notification_history (id, provider_id, service_id, incident_id, message)
	VALUES (?, ?, ?, ?, ?)
	RETURNING id, provider_id, service_id, incident_id, message, status, response, attempts, error_message, last_attempt_at, sent_at, created_at, updated_at
`

type CreateParams struct {
	ID         string  `db:"id" json:"id"`
	ProviderID string  `db:"provider_id" json:"provider_id"`
	ServiceID  *string `db:"service_id" json:"service_id"`
	IncidentID *string `db:"incident_id" json:"incident_id"`
	Message    string  `db:"message" json:"message"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.NotificationHistory, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.ProviderID,
		arg.ServiceID,
		arg.IncidentID,
		arg.Message,
	)
	var i models.NotificationHistory
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ServiceID,
		&i.IncidentID,
		&i.Message,
		&i.Status,
		&i.Response,
		&i.Attempts,
		&i.ErrorMessage,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM notification_history WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}
