// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_history.sql

package repo_notification_history

import (
	"context"
	"time"

	"github.com/sxwebdev/sentinel/internal/models"
	"github.com/sxwebdev/sentinel/internal/store/storecmn"
)

const getAllUnsent = `-- name: GetAllUnsent :many
SELECT
    h.id, h.alert_id, h.provider_id, h.message, h.status, h.response, h.attempts, h.error_message, h.last_attempt_at, h.sent_at, h.created_at, h.updated_at,
    p.provider_type,
    p.config
  FROM notification_history h
  LEFT JOIN notification_providers p ON p.id = h.provider_id
  WHERE
    h.status != 'sent' AND
    p.is_enabled = true
  ORDER BY h.created_at ASC
  LIMIT 100
`

type GetAllUnsentRow struct {
	ID            string                          `db:"id" json:"id"`
	AlertID       *string                         `db:"alert_id" json:"alert_id"`
	ProviderID    string                          `db:"provider_id" json:"provider_id"`
	Message       string                          `db:"message" json:"message"`
	Status        string                          `db:"status" json:"status"`
	Response      *string                         `db:"response" json:"response"`
	Attempts      int64                           `db:"attempts" json:"attempts"`
	ErrorMessage  *string                         `db:"error_message" json:"error_message"`
	LastAttemptAt *time.Time                      `db:"last_attempt_at" json:"last_attempt_at"`
	SentAt        *time.Time                      `db:"sent_at" json:"sent_at"`
	CreatedAt     time.Time                       `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time                       `db:"updated_at" json:"updated_at"`
	ProviderType  models.NotificationProviderType `db:"provider_type" json:"provider_type"`
	Config        storecmn.JSONField              `db:"config" json:"config"`
}

func (q *Queries) GetAllUnsent(ctx context.Context) ([]*GetAllUnsentRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUnsent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAllUnsentRow{}
	for rows.Next() {
		var i GetAllUnsentRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.ProviderID,
			&i.Message,
			&i.Status,
			&i.Response,
			&i.Attempts,
			&i.ErrorMessage,
			&i.LastAttemptAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderType,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAttempt = `-- name: IncrementAttempt :exec
UPDATE notification_history
  SET
    response = ?,
    attempts = attempts + 1,
    error_message = ?,
    last_attempt_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
  WHERE id = ?
`

type IncrementAttemptParams struct {
	Response     *string `db:"response" json:"response"`
	ErrorMessage *string `db:"error_message" json:"error_message"`
	ID           string  `db:"id" json:"id"`
}

func (q *Queries) IncrementAttempt(ctx context.Context, arg IncrementAttemptParams) error {
	_, err := q.db.ExecContext(ctx, incrementAttempt, arg.Response, arg.ErrorMessage, arg.ID)
	return err
}

const markAsSent = `-- name: MarkAsSent :exec
UPDATE notification_history
  SET
    status = 'sent',
    response = ?,
    attempts = attempts + 1,
    error_message = NULL,
    last_attempt_at = CURRENT_TIMESTAMP,
    sent_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
  WHERE id = ?
`

func (q *Queries) MarkAsSent(ctx context.Context, response *string, iD string) error {
	_, err := q.db.ExecContext(ctx, markAsSent, response, iD)
	return err
}
