// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_notification_history

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.NotificationHistory, error)
	DeleteAllByProjectID(ctx context.Context, projectID string) error
	GetAllUnsent(ctx context.Context) ([]*GetAllUnsentRow, error)
	IncrementAttempt(ctx context.Context, arg IncrementAttemptParams) error
	MarkAsSent(ctx context.Context, response *string, iD string) error
}

var _ Querier = (*Queries)(nil)
