// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_notification_history

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.NotificationHistory, error)
	Delete(ctx context.Context, id string) error
	GetByID(ctx context.Context, id string) (*models.NotificationHistory, error)
}

var _ Querier = (*Queries)(nil)
