// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: sentinel/system/v1/service.proto

package systemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AvailableUpdate represents information about an available update
type AvailableUpdate struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	CurrentVersion string                   `protobuf:"bytes,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	IsAvailable    bool                     `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	Details        *AvailableUpdate_Details `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AvailableUpdate) Reset() {
	*x = AvailableUpdate{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableUpdate) ProtoMessage() {}

func (x *AvailableUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableUpdate.ProtoReflect.Descriptor instead.
func (*AvailableUpdate) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *AvailableUpdate) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *AvailableUpdate) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *AvailableUpdate) GetDetails() *AvailableUpdate_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

// SystemInfo represents information about the server
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	BuildDate     string                 `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	GoVersion     string                 `protobuf:"bytes,4,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	SqliteVersion string                 `protobuf:"bytes,5,opt,name=sqlite_version,json=sqliteVersion,proto3" json:"sqlite_version,omitempty"`
	Os            string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname      string                 `protobuf:"bytes,8,opt,name=hostname,proto3" json:"hostname,omitempty"`
	KernelVersion string                 `protobuf:"bytes,9,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	CpuModel      string                 `protobuf:"bytes,10,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	IpAddress     string                 `protobuf:"bytes,11,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfo) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *SystemInfo) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *SystemInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *SystemInfo) GetSqliteVersion() string {
	if x != nil {
		return x.SqliteVersion
	}
	return ""
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SystemInfo) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *SystemInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SystemInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// CheckIsInitializedRequest
type CheckIsInitializedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIsInitializedRequest) Reset() {
	*x = CheckIsInitializedRequest{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIsInitializedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsInitializedRequest) ProtoMessage() {}

func (x *CheckIsInitializedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsInitializedRequest.ProtoReflect.Descriptor instead.
func (*CheckIsInitializedRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{2}
}

type CheckIsInitializedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInitialized bool                   `protobuf:"varint,1,opt,name=is_initialized,json=isInitialized,proto3" json:"is_initialized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIsInitializedResponse) Reset() {
	*x = CheckIsInitializedResponse{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIsInitializedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsInitializedResponse) ProtoMessage() {}

func (x *CheckIsInitializedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsInitializedResponse.ProtoReflect.Descriptor instead.
func (*CheckIsInitializedResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckIsInitializedResponse) GetIsInitialized() bool {
	if x != nil {
		return x.IsInitialized
	}
	return false
}

// InitializeRequest
type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *InitializeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InitializeRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{5}
}

// GetSystemInfoRequest
type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{6}
}

type GetSystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *SystemInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetSystemInfoResponse) GetInfo() *SystemInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// CheckForUpdatesRequest
type CheckForUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckForUpdatesRequest) Reset() {
	*x = CheckForUpdatesRequest{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdatesRequest) ProtoMessage() {}

func (x *CheckForUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdatesRequest.ProtoReflect.Descriptor instead.
func (*CheckForUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{8}
}

type CheckForUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *AvailableUpdate       `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckForUpdatesResponse) Reset() {
	*x = CheckForUpdatesResponse{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdatesResponse) ProtoMessage() {}

func (x *CheckForUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdatesResponse.ProtoReflect.Descriptor instead.
func (*CheckForUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *CheckForUpdatesResponse) GetInfo() *AvailableUpdate {
	if x != nil {
		return x.Info
	}
	return nil
}

type AvailableUpdate_Details struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsAvailableManual bool                   `protobuf:"varint,1,opt,name=is_available_manual,json=isAvailableManual,proto3" json:"is_available_manual,omitempty"`
	TagName           string                 `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	Url               string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AvailableUpdate_Details) Reset() {
	*x = AvailableUpdate_Details{}
	mi := &file_sentinel_system_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableUpdate_Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableUpdate_Details) ProtoMessage() {}

func (x *AvailableUpdate_Details) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_system_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableUpdate_Details.ProtoReflect.Descriptor instead.
func (*AvailableUpdate_Details) Descriptor() ([]byte, []int) {
	return file_sentinel_system_v1_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AvailableUpdate_Details) GetIsAvailableManual() bool {
	if x != nil {
		return x.IsAvailableManual
	}
	return false
}

func (x *AvailableUpdate_Details) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *AvailableUpdate_Details) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AvailableUpdate_Details) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_sentinel_system_v1_service_proto protoreflect.FileDescriptor

const file_sentinel_system_v1_service_proto_rawDesc = "" +
	"\n" +
	" sentinel/system/v1/service.proto\x12\x12sentinel.system.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\x0fAvailableUpdate\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\tR\x0ecurrentVersion\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable\x12E\n" +
	"\adetails\x18\x03 \x01(\v2+.sentinel.system.v1.AvailableUpdate.DetailsR\adetails\x1a\x88\x01\n" +
	"\aDetails\x12.\n" +
	"\x13is_available_manual\x18\x01 \x01(\bR\x11isAvailableManual\x12\x19\n" +
	"\btag_name\x18\x02 \x01(\tR\atagName\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x8a\x03\n" +
	"\n" +
	"SystemInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\x12\x1d\n" +
	"\n" +
	"go_version\x18\x04 \x01(\tR\tgoVersion\x12%\n" +
	"\x0esqlite_version\x18\x05 \x01(\tR\rsqliteVersion\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\b \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_version\x18\t \x01(\tR\rkernelVersion\x12\x1b\n" +
	"\tcpu_model\x18\n" +
	" \x01(\tR\bcpuModel\x12\x1d\n" +
	"\n" +
	"ip_address\x18\v \x01(\tR\tipAddress\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\x1b\n" +
	"\x19CheckIsInitializedRequest\"C\n" +
	"\x1aCheckIsInitializedResponse\x12%\n" +
	"\x0eis_initialized\x18\x01 \x01(\bR\risInitialized\"E\n" +
	"\x11InitializeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x14\n" +
	"\x12InitializeResponse\"\x16\n" +
	"\x14GetSystemInfoRequest\"K\n" +
	"\x15GetSystemInfoResponse\x122\n" +
	"\x04info\x18\x01 \x01(\v2\x1e.sentinel.system.v1.SystemInfoR\x04info\"\x18\n" +
	"\x16CheckForUpdatesRequest\"R\n" +
	"\x17CheckForUpdatesResponse\x127\n" +
	"\x04info\x18\x01 \x01(\v2#.sentinel.system.v1.AvailableUpdateR\x04info2\xb3\x03\n" +
	"\rSystemService\x12s\n" +
	"\x12CheckIsInitialized\x12-.sentinel.system.v1.CheckIsInitializedRequest\x1a..sentinel.system.v1.CheckIsInitializedResponse\x12[\n" +
	"\n" +
	"Initialize\x12%.sentinel.system.v1.InitializeRequest\x1a&.sentinel.system.v1.InitializeResponse\x12d\n" +
	"\rGetSystemInfo\x12(.sentinel.system.v1.GetSystemInfoRequest\x1a).sentinel.system.v1.GetSystemInfoResponse\x12j\n" +
	"\x0fCheckForUpdates\x12*.sentinel.system.v1.CheckForUpdatesRequest\x1a+.sentinel.system.v1.CheckForUpdatesResponseB\xe5\x01\n" +
	"\x16com.sentinel.system.v1B\fServiceProtoP\x01ZSgithub.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/system/v1;systemv1\xa2\x02\x03SSX\xaa\x02\x12Sentinel.System.V1\xca\x02\x12Sentinel\\System\\V1\xe2\x02\x1eSentinel\\System\\V1\\GPBMetadata\xea\x02\x14Sentinel::System::V1b\x06proto3"

var (
	file_sentinel_system_v1_service_proto_rawDescOnce sync.Once
	file_sentinel_system_v1_service_proto_rawDescData []byte
)

func file_sentinel_system_v1_service_proto_rawDescGZIP() []byte {
	file_sentinel_system_v1_service_proto_rawDescOnce.Do(func() {
		file_sentinel_system_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinel_system_v1_service_proto_rawDesc), len(file_sentinel_system_v1_service_proto_rawDesc)))
	})
	return file_sentinel_system_v1_service_proto_rawDescData
}

var file_sentinel_system_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sentinel_system_v1_service_proto_goTypes = []any{
	(*AvailableUpdate)(nil),            // 0: sentinel.system.v1.AvailableUpdate
	(*SystemInfo)(nil),                 // 1: sentinel.system.v1.SystemInfo
	(*CheckIsInitializedRequest)(nil),  // 2: sentinel.system.v1.CheckIsInitializedRequest
	(*CheckIsInitializedResponse)(nil), // 3: sentinel.system.v1.CheckIsInitializedResponse
	(*InitializeRequest)(nil),          // 4: sentinel.system.v1.InitializeRequest
	(*InitializeResponse)(nil),         // 5: sentinel.system.v1.InitializeResponse
	(*GetSystemInfoRequest)(nil),       // 6: sentinel.system.v1.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil),      // 7: sentinel.system.v1.GetSystemInfoResponse
	(*CheckForUpdatesRequest)(nil),     // 8: sentinel.system.v1.CheckForUpdatesRequest
	(*CheckForUpdatesResponse)(nil),    // 9: sentinel.system.v1.CheckForUpdatesResponse
	(*AvailableUpdate_Details)(nil),    // 10: sentinel.system.v1.AvailableUpdate.Details
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_sentinel_system_v1_service_proto_depIdxs = []int32{
	10, // 0: sentinel.system.v1.AvailableUpdate.details:type_name -> sentinel.system.v1.AvailableUpdate.Details
	11, // 1: sentinel.system.v1.SystemInfo.started_at:type_name -> google.protobuf.Timestamp
	1,  // 2: sentinel.system.v1.GetSystemInfoResponse.info:type_name -> sentinel.system.v1.SystemInfo
	0,  // 3: sentinel.system.v1.CheckForUpdatesResponse.info:type_name -> sentinel.system.v1.AvailableUpdate
	2,  // 4: sentinel.system.v1.SystemService.CheckIsInitialized:input_type -> sentinel.system.v1.CheckIsInitializedRequest
	4,  // 5: sentinel.system.v1.SystemService.Initialize:input_type -> sentinel.system.v1.InitializeRequest
	6,  // 6: sentinel.system.v1.SystemService.GetSystemInfo:input_type -> sentinel.system.v1.GetSystemInfoRequest
	8,  // 7: sentinel.system.v1.SystemService.CheckForUpdates:input_type -> sentinel.system.v1.CheckForUpdatesRequest
	3,  // 8: sentinel.system.v1.SystemService.CheckIsInitialized:output_type -> sentinel.system.v1.CheckIsInitializedResponse
	5,  // 9: sentinel.system.v1.SystemService.Initialize:output_type -> sentinel.system.v1.InitializeResponse
	7,  // 10: sentinel.system.v1.SystemService.GetSystemInfo:output_type -> sentinel.system.v1.GetSystemInfoResponse
	9,  // 11: sentinel.system.v1.SystemService.CheckForUpdates:output_type -> sentinel.system.v1.CheckForUpdatesResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_sentinel_system_v1_service_proto_init() }
func file_sentinel_system_v1_service_proto_init() {
	if File_sentinel_system_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinel_system_v1_service_proto_rawDesc), len(file_sentinel_system_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentinel_system_v1_service_proto_goTypes,
		DependencyIndexes: file_sentinel_system_v1_service_proto_depIdxs,
		MessageInfos:      file_sentinel_system_v1_service_proto_msgTypes,
	}.Build()
	File_sentinel_system_v1_service_proto = out.File
	file_sentinel_system_v1_service_proto_goTypes = nil
	file_sentinel_system_v1_service_proto_depIdxs = nil
}
