// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.13
package repo_incidents

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameIncidents TableName = "incidents"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameIncidentsId          ColumnName = "id"
	ColumnNameIncidentsProjectId   ColumnName = "project_id"
	ColumnNameIncidentsOrigin      ColumnName = "origin"
	ColumnNameIncidentsMonitorId   ColumnName = "monitor_id"
	ColumnNameIncidentsResourceId  ColumnName = "resource_id"
	ColumnNameIncidentsAgentId     ColumnName = "agent_id"
	ColumnNameIncidentsKind        ColumnName = "kind"
	ColumnNameIncidentsStatus      ColumnName = "status"
	ColumnNameIncidentsSeverity    ColumnName = "severity"
	ColumnNameIncidentsSummary     ColumnName = "summary"
	ColumnNameIncidentsFirstSeenAt ColumnName = "first_seen_at"
	ColumnNameIncidentsLastSeenAt  ColumnName = "last_seen_at"
	ColumnNameIncidentsResolvedAt  ColumnName = "resolved_at"
	ColumnNameIncidentsCreatedAt   ColumnName = "created_at"
	ColumnNameIncidentsUpdatedAt   ColumnName = "updated_at"
)

func IncidentsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameIncidentsId,
		ColumnNameIncidentsProjectId,
		ColumnNameIncidentsOrigin,
		ColumnNameIncidentsMonitorId,
		ColumnNameIncidentsResourceId,
		ColumnNameIncidentsAgentId,
		ColumnNameIncidentsKind,
		ColumnNameIncidentsStatus,
		ColumnNameIncidentsSeverity,
		ColumnNameIncidentsSummary,
		ColumnNameIncidentsFirstSeenAt,
		ColumnNameIncidentsLastSeenAt,
		ColumnNameIncidentsResolvedAt,
		ColumnNameIncidentsCreatedAt,
		ColumnNameIncidentsUpdatedAt,
	}
}
