// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents.sql

package repo_incidents

import (
	"context"
	"time"

	"github.com/sxwebdev/sentinel/internal/models"
)

const deleteByServiceID = `-- name: DeleteByServiceID :exec
DELETE FROM incidents WHERE service_id=?
`

func (q *Queries) DeleteByServiceID(ctx context.Context, serviceID string) error {
	_, err := q.db.ExecContext(ctx, deleteByServiceID, serviceID)
	return err
}

const getAllUnresolvedByServiceID = `-- name: GetAllUnresolvedByServiceID :many
SELECT id, service_id, error, duration, started_at, resolved_at, created_at, updated_at FROM incidents
WHERE service_id=? AND resolved_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllUnresolvedByServiceID(ctx context.Context, serviceID string) ([]*models.Incident, error) {
	rows, err := q.db.QueryContext(ctx, getAllUnresolvedByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Incident{}
	for rows.Next() {
		var i models.Incident
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Error,
			&i.Duration,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveByID = `-- name: ResolveByID :exec
UPDATE incidents
SET
  resolved_at = CURRENT_TIMESTAMP,
  duration = CAST((julianday('now') - julianday(started_at)) * 86400000 AS INTEGER),
  updated_at = CURRENT_TIMESTAMP
WHERE id=? AND resolved_at IS NULL
`

func (q *Queries) ResolveByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, resolveByID, id)
	return err
}

const stats = `-- name: Stats :one
SELECT
 	COUNT(*) AS total_incidents,
 	SUM(duration) AS total_downtime,
  AVG(duration) AS avg_downtime,
  SUM(CASE WHEN resolved_at IS NOT NULL THEN 1 ELSE 0 END) AS resolved_incidents,
  SUM(CASE WHEN resolved_at IS NULL THEN 1 ELSE 0 END) AS unresolved_incidents
FROM incidents
`

type StatsRow struct {
	TotalIncidents      int64    `db:"total_incidents" json:"total_incidents"`
	TotalDowntime       *float64 `db:"total_downtime" json:"total_downtime"`
	AvgDowntime         *float64 `db:"avg_downtime" json:"avg_downtime"`
	ResolvedIncidents   *float64 `db:"resolved_incidents" json:"resolved_incidents"`
	UnresolvedIncidents *float64 `db:"unresolved_incidents" json:"unresolved_incidents"`
}

func (q *Queries) Stats(ctx context.Context) (*StatsRow, error) {
	row := q.db.QueryRowContext(ctx, stats)
	var i StatsRow
	err := row.Scan(
		&i.TotalIncidents,
		&i.TotalDowntime,
		&i.AvgDowntime,
		&i.ResolvedIncidents,
		&i.UnresolvedIncidents,
	)
	return &i, err
}

const statsByServiceID = `-- name: StatsByServiceID :one
SELECT
 	COUNT(*) AS total_incidents,
 	SUM(duration) AS total_downtime,
  AVG(duration) AS avg_downtime,
  SUM(CASE WHEN resolved_at IS NOT NULL THEN 1 ELSE 0 END) AS resolved_incidents,
  SUM(CASE WHEN resolved_at IS NULL THEN 1 ELSE 0 END) AS unresolved_incidents,
  ROUND(100.0 - (COALESCE(SUM(duration), 0) * 100.0 / (30 * 24 * 60 * 60 * 1000)), 3) AS uptime_percentage_30d
FROM incidents
WHERE service_id=? AND created_at >= ?
`

type StatsByServiceIDRow struct {
	TotalIncidents      int64    `db:"total_incidents" json:"total_incidents"`
	TotalDowntime       *float64 `db:"total_downtime" json:"total_downtime"`
	AvgDowntime         *float64 `db:"avg_downtime" json:"avg_downtime"`
	ResolvedIncidents   *float64 `db:"resolved_incidents" json:"resolved_incidents"`
	UnresolvedIncidents *float64 `db:"unresolved_incidents" json:"unresolved_incidents"`
	UptimePercentage30d float64  `db:"uptime_percentage_30d" json:"uptime_percentage_30d"`
}

func (q *Queries) StatsByServiceID(ctx context.Context, serviceID string, createdAt time.Time) (*StatsByServiceIDRow, error) {
	row := q.db.QueryRowContext(ctx, statsByServiceID, serviceID, createdAt)
	var i StatsByServiceIDRow
	err := row.Scan(
		&i.TotalIncidents,
		&i.TotalDowntime,
		&i.AvgDowntime,
		&i.ResolvedIncidents,
		&i.UnresolvedIncidents,
		&i.UptimePercentage30d,
	)
	return &i, err
}
