// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents.sql

package repo_incidents

import (
	"context"
)

const deleteByServiceID = `-- name: DeleteByServiceID :exec
DELETE FROM incidents WHERE service_id=?
`

func (q *Queries) DeleteByServiceID(ctx context.Context, serviceID string) error {
	_, err := q.db.ExecContext(ctx, deleteByServiceID, serviceID)
	return err
}
