// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents_gen.sql

package repo_incidents

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

const create = `-- name: Create :one
INSERT INTO incidents (id, service_id, error)
	VALUES (?, ?, ?3)
	RETURNING id, service_id, error, duration, started_at, resolved_at, created_at, updated_at
`

func (q *Queries) Create(ctx context.Context, iD string, serviceID string, incidentError string) (*models.Incident, error) {
	row := q.db.QueryRowContext(ctx, create, iD, serviceID, incidentError)
	var i models.Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Error,
		&i.Duration,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM incidents WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, service_id, error, duration, started_at, resolved_at, created_at, updated_at FROM incidents WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Incident, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Error,
		&i.Duration,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
