// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_incidents

import (
	"context"
	"time"

	"github.com/sxwebdev/sentinel/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Incident, error)
	Delete(ctx context.Context, id string) error
	DeleteByServiceID(ctx context.Context, serviceID string) error
	GetByID(ctx context.Context, id string) (*models.Incident, error)
	StatsByServiceID(ctx context.Context, serviceID string, startTime time.Time) (*StatsByServiceIDRow, error)
}

var _ Querier = (*Queries)(nil)
