// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sentinel/auth/v1/auth.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "sentinel.auth.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceAuthorizationProcedure is the fully-qualified name of the AuthService's Authorization
	// RPC.
	AuthServiceAuthorizationProcedure = "/sentinel.auth.v1.AuthService/Authorization"
	// AuthServiceAuthenticateProcedure is the fully-qualified name of the AuthService's Authenticate
	// RPC.
	AuthServiceAuthenticateProcedure = "/sentinel.auth.v1.AuthService/Authenticate"
	// AuthServiceRefreshTokenProcedure is the fully-qualified name of the AuthService's RefreshToken
	// RPC.
	AuthServiceRefreshTokenProcedure = "/sentinel.auth.v1.AuthService/RefreshToken"
	// AuthServiceLogoutProcedure is the fully-qualified name of the AuthService's Logout RPC.
	AuthServiceLogoutProcedure = "/sentinel.auth.v1.AuthService/Logout"
	// AuthServiceActiveSessionsProcedure is the fully-qualified name of the AuthService's
	// ActiveSessions RPC.
	AuthServiceActiveSessionsProcedure = "/sentinel.auth.v1.AuthService/ActiveSessions"
	// AuthServiceDeleteSessionProcedure is the fully-qualified name of the AuthService's DeleteSession
	// RPC.
	AuthServiceDeleteSessionProcedure = "/sentinel.auth.v1.AuthService/DeleteSession"
	// AuthServiceTerminateAllSessionsProcedure is the fully-qualified name of the AuthService's
	// TerminateAllSessions RPC.
	AuthServiceTerminateAllSessionsProcedure = "/sentinel.auth.v1.AuthService/TerminateAllSessions"
)

// AuthServiceClient is a client for the sentinel.auth.v1.AuthService service.
type AuthServiceClient interface {
	// Auth
	Authorization(context.Context, *connect.Request[v1.AuthorizationRequest]) (*connect.Response[v1.AuthorizationResponse], error)
	Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error)
	RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
	// Sessions
	ActiveSessions(context.Context, *connect.Request[v1.ActiveSessionsRequest]) (*connect.Response[v1.ActiveSessionsResponse], error)
	DeleteSession(context.Context, *connect.Request[v1.DeleteSessionRequest]) (*connect.Response[v1.DeleteSessionResponse], error)
	TerminateAllSessions(context.Context, *connect.Request[v1.TerminateAllSessionsRequest]) (*connect.Response[v1.TerminateAllSessionsResponse], error)
}

// NewAuthServiceClient constructs a client for the sentinel.auth.v1.AuthService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_sentinel_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		authorization: connect.NewClient[v1.AuthorizationRequest, v1.AuthorizationResponse](
			httpClient,
			baseURL+AuthServiceAuthorizationProcedure,
			connect.WithSchema(authServiceMethods.ByName("Authorization")),
			connect.WithClientOptions(opts...),
		),
		authenticate: connect.NewClient[v1.AuthenticateRequest, v1.AuthenticateResponse](
			httpClient,
			baseURL+AuthServiceAuthenticateProcedure,
			connect.WithSchema(authServiceMethods.ByName("Authenticate")),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[v1.RefreshTokenRequest, v1.RefreshTokenResponse](
			httpClient,
			baseURL+AuthServiceRefreshTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v1.LogoutRequest, v1.LogoutResponse](
			httpClient,
			baseURL+AuthServiceLogoutProcedure,
			connect.WithSchema(authServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		activeSessions: connect.NewClient[v1.ActiveSessionsRequest, v1.ActiveSessionsResponse](
			httpClient,
			baseURL+AuthServiceActiveSessionsProcedure,
			connect.WithSchema(authServiceMethods.ByName("ActiveSessions")),
			connect.WithClientOptions(opts...),
		),
		deleteSession: connect.NewClient[v1.DeleteSessionRequest, v1.DeleteSessionResponse](
			httpClient,
			baseURL+AuthServiceDeleteSessionProcedure,
			connect.WithSchema(authServiceMethods.ByName("DeleteSession")),
			connect.WithClientOptions(opts...),
		),
		terminateAllSessions: connect.NewClient[v1.TerminateAllSessionsRequest, v1.TerminateAllSessionsResponse](
			httpClient,
			baseURL+AuthServiceTerminateAllSessionsProcedure,
			connect.WithSchema(authServiceMethods.ByName("TerminateAllSessions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	authorization        *connect.Client[v1.AuthorizationRequest, v1.AuthorizationResponse]
	authenticate         *connect.Client[v1.AuthenticateRequest, v1.AuthenticateResponse]
	refreshToken         *connect.Client[v1.RefreshTokenRequest, v1.RefreshTokenResponse]
	logout               *connect.Client[v1.LogoutRequest, v1.LogoutResponse]
	activeSessions       *connect.Client[v1.ActiveSessionsRequest, v1.ActiveSessionsResponse]
	deleteSession        *connect.Client[v1.DeleteSessionRequest, v1.DeleteSessionResponse]
	terminateAllSessions *connect.Client[v1.TerminateAllSessionsRequest, v1.TerminateAllSessionsResponse]
}

// Authorization calls sentinel.auth.v1.AuthService.Authorization.
func (c *authServiceClient) Authorization(ctx context.Context, req *connect.Request[v1.AuthorizationRequest]) (*connect.Response[v1.AuthorizationResponse], error) {
	return c.authorization.CallUnary(ctx, req)
}

// Authenticate calls sentinel.auth.v1.AuthService.Authenticate.
func (c *authServiceClient) Authenticate(ctx context.Context, req *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error) {
	return c.authenticate.CallUnary(ctx, req)
}

// RefreshToken calls sentinel.auth.v1.AuthService.RefreshToken.
func (c *authServiceClient) RefreshToken(ctx context.Context, req *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// Logout calls sentinel.auth.v1.AuthService.Logout.
func (c *authServiceClient) Logout(ctx context.Context, req *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// ActiveSessions calls sentinel.auth.v1.AuthService.ActiveSessions.
func (c *authServiceClient) ActiveSessions(ctx context.Context, req *connect.Request[v1.ActiveSessionsRequest]) (*connect.Response[v1.ActiveSessionsResponse], error) {
	return c.activeSessions.CallUnary(ctx, req)
}

// DeleteSession calls sentinel.auth.v1.AuthService.DeleteSession.
func (c *authServiceClient) DeleteSession(ctx context.Context, req *connect.Request[v1.DeleteSessionRequest]) (*connect.Response[v1.DeleteSessionResponse], error) {
	return c.deleteSession.CallUnary(ctx, req)
}

// TerminateAllSessions calls sentinel.auth.v1.AuthService.TerminateAllSessions.
func (c *authServiceClient) TerminateAllSessions(ctx context.Context, req *connect.Request[v1.TerminateAllSessionsRequest]) (*connect.Response[v1.TerminateAllSessionsResponse], error) {
	return c.terminateAllSessions.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the sentinel.auth.v1.AuthService service.
type AuthServiceHandler interface {
	// Auth
	Authorization(context.Context, *connect.Request[v1.AuthorizationRequest]) (*connect.Response[v1.AuthorizationResponse], error)
	Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error)
	RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
	// Sessions
	ActiveSessions(context.Context, *connect.Request[v1.ActiveSessionsRequest]) (*connect.Response[v1.ActiveSessionsResponse], error)
	DeleteSession(context.Context, *connect.Request[v1.DeleteSessionRequest]) (*connect.Response[v1.DeleteSessionResponse], error)
	TerminateAllSessions(context.Context, *connect.Request[v1.TerminateAllSessionsRequest]) (*connect.Response[v1.TerminateAllSessionsResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_sentinel_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceAuthorizationHandler := connect.NewUnaryHandler(
		AuthServiceAuthorizationProcedure,
		svc.Authorization,
		connect.WithSchema(authServiceMethods.ByName("Authorization")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceAuthenticateHandler := connect.NewUnaryHandler(
		AuthServiceAuthenticateProcedure,
		svc.Authenticate,
		connect.WithSchema(authServiceMethods.ByName("Authenticate")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRefreshTokenHandler := connect.NewUnaryHandler(
		AuthServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutHandler := connect.NewUnaryHandler(
		AuthServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(authServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceActiveSessionsHandler := connect.NewUnaryHandler(
		AuthServiceActiveSessionsProcedure,
		svc.ActiveSessions,
		connect.WithSchema(authServiceMethods.ByName("ActiveSessions")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDeleteSessionHandler := connect.NewUnaryHandler(
		AuthServiceDeleteSessionProcedure,
		svc.DeleteSession,
		connect.WithSchema(authServiceMethods.ByName("DeleteSession")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceTerminateAllSessionsHandler := connect.NewUnaryHandler(
		AuthServiceTerminateAllSessionsProcedure,
		svc.TerminateAllSessions,
		connect.WithSchema(authServiceMethods.ByName("TerminateAllSessions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sentinel.auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceAuthorizationProcedure:
			authServiceAuthorizationHandler.ServeHTTP(w, r)
		case AuthServiceAuthenticateProcedure:
			authServiceAuthenticateHandler.ServeHTTP(w, r)
		case AuthServiceRefreshTokenProcedure:
			authServiceRefreshTokenHandler.ServeHTTP(w, r)
		case AuthServiceLogoutProcedure:
			authServiceLogoutHandler.ServeHTTP(w, r)
		case AuthServiceActiveSessionsProcedure:
			authServiceActiveSessionsHandler.ServeHTTP(w, r)
		case AuthServiceDeleteSessionProcedure:
			authServiceDeleteSessionHandler.ServeHTTP(w, r)
		case AuthServiceTerminateAllSessionsProcedure:
			authServiceTerminateAllSessionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Authorization(context.Context, *connect.Request[v1.AuthorizationRequest]) (*connect.Response[v1.AuthorizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.auth.v1.AuthService.Authorization is not implemented"))
}

func (UnimplementedAuthServiceHandler) Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.auth.v1.AuthService.Authenticate is not implemented"))
}

func (UnimplementedAuthServiceHandler) RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.auth.v1.AuthService.RefreshToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.auth.v1.AuthService.Logout is not implemented"))
}

func (UnimplementedAuthServiceHandler) ActiveSessions(context.Context, *connect.Request[v1.ActiveSessionsRequest]) (*connect.Response[v1.ActiveSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.auth.v1.AuthService.ActiveSessions is not implemented"))
}

func (UnimplementedAuthServiceHandler) DeleteSession(context.Context, *connect.Request[v1.DeleteSessionRequest]) (*connect.Response[v1.DeleteSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.auth.v1.AuthService.DeleteSession is not implemented"))
}

func (UnimplementedAuthServiceHandler) TerminateAllSessions(context.Context, *connect.Request[v1.TerminateAllSessionsRequest]) (*connect.Response[v1.TerminateAllSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.auth.v1.AuthService.TerminateAllSessions is not implemented"))
}
