// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.13
package repo_notification_providers

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameNotificationProviders TableName = "notification_providers"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameNotificationProvidersId           ColumnName = "id"
	ColumnNameNotificationProvidersProviderType ColumnName = "provider_type"
	ColumnNameNotificationProvidersConfig       ColumnName = "config"
	ColumnNameNotificationProvidersIsEnabled    ColumnName = "is_enabled"
	ColumnNameNotificationProvidersProjectId    ColumnName = "project_id"
	ColumnNameNotificationProvidersCreatedAt    ColumnName = "created_at"
	ColumnNameNotificationProvidersUpdatedAt    ColumnName = "updated_at"
)

func NotificationProvidersColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameNotificationProvidersId,
		ColumnNameNotificationProvidersProviderType,
		ColumnNameNotificationProvidersConfig,
		ColumnNameNotificationProvidersIsEnabled,
		ColumnNameNotificationProvidersProjectId,
		ColumnNameNotificationProvidersCreatedAt,
		ColumnNameNotificationProvidersUpdatedAt,
	}
}
