// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_providers.sql

package repo_notification_providers

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
	"github.com/sxwebdev/sentinel/internal/store/storecmn"
)

const getAllEnabled = `-- name: GetAllEnabled :many
SELECT id, provider_type, json(config), is_enabled, created_at, updated_at FROM notification_providers WHERE is_enabled=true
`

func (q *Queries) GetAllEnabled(ctx context.Context) ([]*models.NotificationProvider, error) {
	rows, err := q.db.QueryContext(ctx, getAllEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.NotificationProvider{}
	for rows.Next() {
		var i models.NotificationProvider
		if err := rows.Scan(
			&i.ID,
			&i.ProviderType,
			&i.Config,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :exec
UPDATE notification_providers
  SET
    provider_type = ?,
    config = ?,
    is_enabled = ?,
    updated_at = CURRENT_TIMESTAMP
  WHERE id = ?
`

type UpdateParams struct {
	ProviderType models.NotificationProviderType `db:"provider_type" json:"provider_type"`
	Config       storecmn.JSONField              `db:"config" json:"config"`
	IsEnabled    bool                            `db:"is_enabled" json:"is_enabled"`
	ID           string                          `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.ExecContext(ctx, update,
		arg.ProviderType,
		arg.Config,
		arg.IsEnabled,
		arg.ID,
	)
	return err
}
