// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_providers_gen.sql

package repo_notification_providers

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
	"github.com/sxwebdev/sentinel/internal/store/storecmn"
)

const create = `-- name: Create :one
INSERT INTO notification_providers (id, provider_type, config, is_enabled, project_id)
	VALUES (?, ?, ?, ?, ?)
	RETURNING id, provider_type, config, is_enabled, project_id, created_at, updated_at
`

type CreateParams struct {
	ID           string                          `db:"id" json:"id"`
	ProviderType models.NotificationProviderType `db:"provider_type" json:"provider_type"`
	Config       storecmn.JSONField              `db:"config" json:"config"`
	IsEnabled    bool                            `db:"is_enabled" json:"is_enabled"`
	ProjectID    string                          `db:"project_id" json:"project_id"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.NotificationProvider, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.ProviderType,
		arg.Config,
		arg.IsEnabled,
		arg.ProjectID,
	)
	var i models.NotificationProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderType,
		&i.Config,
		&i.IsEnabled,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM notification_providers WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, provider_type, config, is_enabled, project_id, created_at, updated_at FROM notification_providers WHERE project_id=?
`

func (q *Queries) GetAll(ctx context.Context, projectID string) ([]*models.NotificationProvider, error) {
	rows, err := q.db.QueryContext(ctx, getAll, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.NotificationProvider{}
	for rows.Next() {
		var i models.NotificationProvider
		if err := rows.Scan(
			&i.ID,
			&i.ProviderType,
			&i.Config,
			&i.IsEnabled,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, provider_type, config, is_enabled, project_id, created_at, updated_at FROM notification_providers WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.NotificationProvider, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.NotificationProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderType,
		&i.Config,
		&i.IsEnabled,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
