// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_notification_providers

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.NotificationProvider, error)
	Delete(ctx context.Context, id string) error
	GetAll(ctx context.Context, projectID string) ([]*models.NotificationProvider, error)
	GetAllEnabled(ctx context.Context, projectID string) ([]*models.NotificationProvider, error)
	GetByID(ctx context.Context, id string) (*models.NotificationProvider, error)
	Update(ctx context.Context, arg UpdateParams) error
}

var _ Querier = (*Queries)(nil)
