// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.12
package repo_service_states

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameServiceStates TableName = "service_states"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameServiceStatesId                 ColumnName = "id"
	ColumnNameServiceStatesServiceId          ColumnName = "service_id"
	ColumnNameServiceStatesStatus             ColumnName = "status"
	ColumnNameServiceStatesLastCheck          ColumnName = "last_check"
	ColumnNameServiceStatesLastError          ColumnName = "last_error"
	ColumnNameServiceStatesConsecutiveFails   ColumnName = "consecutive_fails"
	ColumnNameServiceStatesConsecutiveSuccess ColumnName = "consecutive_success"
	ColumnNameServiceStatesTotalChecks        ColumnName = "total_checks"
	ColumnNameServiceStatesAvgResponseTime    ColumnName = "avg_response_time"
	ColumnNameServiceStatesCreatedAt          ColumnName = "created_at"
	ColumnNameServiceStatesUpdatedAt          ColumnName = "updated_at"
)

func ServiceStatesColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameServiceStatesId,
		ColumnNameServiceStatesServiceId,
		ColumnNameServiceStatesStatus,
		ColumnNameServiceStatesLastCheck,
		ColumnNameServiceStatesLastError,
		ColumnNameServiceStatesConsecutiveFails,
		ColumnNameServiceStatesConsecutiveSuccess,
		ColumnNameServiceStatesTotalChecks,
		ColumnNameServiceStatesAvgResponseTime,
		ColumnNameServiceStatesCreatedAt,
		ColumnNameServiceStatesUpdatedAt,
	}
}
