// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_service_states

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.ServiceState, error)
	Delete(ctx context.Context, id string) error
	DeleteByServiceID(ctx context.Context, serviceID string) error
	GetAll(ctx context.Context) ([]*models.ServiceState, error)
	GetByID(ctx context.Context, id string) (*models.ServiceState, error)
	GetByServiceID(ctx context.Context, serviceID string) (*models.ServiceState, error)
}

var _ Querier = (*Queries)(nil)
