// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_states_gen.sql

package repo_service_states

import (
	"context"
	"time"

	"github.com/sxwebdev/sentinel/internal/models"
)

const create = `-- name: Create :one
INSERT INTO service_states (id, service_id, status, last_check, next_check, last_error, consecutive_fails, consecutive_success, total_checks, response_time_ns)
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	RETURNING id, service_id, status, last_check, next_check, last_error, consecutive_fails, consecutive_success, total_checks, response_time_ns, created_at, updated_at
`

type CreateParams struct {
	ID                 string               `db:"id" json:"id"`
	ServiceID          string               `db:"service_id" json:"service_id"`
	Status             models.ServiceStatus `db:"status" json:"status"`
	LastCheck          *time.Time           `db:"last_check" json:"last_check"`
	NextCheck          *time.Time           `db:"next_check" json:"next_check"`
	LastError          *string              `db:"last_error" json:"last_error"`
	ConsecutiveFails   int64                `db:"consecutive_fails" json:"consecutive_fails"`
	ConsecutiveSuccess int64                `db:"consecutive_success" json:"consecutive_success"`
	TotalChecks        int64                `db:"total_checks" json:"total_checks"`
	ResponseTimeNs     *int64               `db:"response_time_ns" json:"response_time_ns"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.ServiceState, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.ServiceID,
		arg.Status,
		arg.LastCheck,
		arg.NextCheck,
		arg.LastError,
		arg.ConsecutiveFails,
		arg.ConsecutiveSuccess,
		arg.TotalChecks,
		arg.ResponseTimeNs,
	)
	var i models.ServiceState
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Status,
		&i.LastCheck,
		&i.NextCheck,
		&i.LastError,
		&i.ConsecutiveFails,
		&i.ConsecutiveSuccess,
		&i.TotalChecks,
		&i.ResponseTimeNs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM service_states WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, service_id, status, last_check, next_check, last_error, consecutive_fails, consecutive_success, total_checks, response_time_ns, created_at, updated_at FROM service_states
`

func (q *Queries) GetAll(ctx context.Context) ([]*models.ServiceState, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.ServiceState{}
	for rows.Next() {
		var i models.ServiceState
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Status,
			&i.LastCheck,
			&i.NextCheck,
			&i.LastError,
			&i.ConsecutiveFails,
			&i.ConsecutiveSuccess,
			&i.TotalChecks,
			&i.ResponseTimeNs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, service_id, status, last_check, next_check, last_error, consecutive_fails, consecutive_success, total_checks, response_time_ns, created_at, updated_at FROM service_states WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.ServiceState, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.ServiceState
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Status,
		&i.LastCheck,
		&i.NextCheck,
		&i.LastError,
		&i.ConsecutiveFails,
		&i.ConsecutiveSuccess,
		&i.TotalChecks,
		&i.ResponseTimeNs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
