// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: sentinel/service/v1/service.proto

package servicev1

import (
	v1 "github.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HTTPConfig struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Endpoints     []*HTTPConfig_EndpointConfig `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Condition     string                       `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPConfig) Reset() {
	*x = HTTPConfig{}
	mi := &file_sentinel_service_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPConfig) ProtoMessage() {}

func (x *HTTPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_service_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPConfig.ProtoReflect.Descriptor instead.
func (*HTTPConfig) Descriptor() ([]byte, []int) {
	return file_sentinel_service_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *HTTPConfig) GetEndpoints() []*HTTPConfig_EndpointConfig {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *HTTPConfig) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type TCPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	SendData      string                 `protobuf:"bytes,2,opt,name=send_data,json=sendData,proto3" json:"send_data,omitempty"`
	ExpectData    string                 `protobuf:"bytes,3,opt,name=expect_data,json=expectData,proto3" json:"expect_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPConfig) Reset() {
	*x = TCPConfig{}
	mi := &file_sentinel_service_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPConfig) ProtoMessage() {}

func (x *TCPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_service_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPConfig.ProtoReflect.Descriptor instead.
func (*TCPConfig) Descriptor() ([]byte, []int) {
	return file_sentinel_service_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *TCPConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *TCPConfig) GetSendData() string {
	if x != nil {
		return x.SendData
	}
	return ""
}

func (x *TCPConfig) GetExpectData() string {
	if x != nil {
		return x.ExpectData
	}
	return ""
}

type GRPCConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CheckType     string                 `protobuf:"bytes,2,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Tls           bool                   `protobuf:"varint,4,opt,name=tls,proto3" json:"tls,omitempty"`
	InsecureTls   bool                   `protobuf:"varint,5,opt,name=insecure_tls,json=insecureTls,proto3" json:"insecure_tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPCConfig) Reset() {
	*x = GRPCConfig{}
	mi := &file_sentinel_service_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCConfig) ProtoMessage() {}

func (x *GRPCConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_service_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCConfig.ProtoReflect.Descriptor instead.
func (*GRPCConfig) Descriptor() ([]byte, []int) {
	return file_sentinel_service_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GRPCConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *GRPCConfig) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *GRPCConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GRPCConfig) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *GRPCConfig) GetInsecureTls() bool {
	if x != nil {
		return x.InsecureTls
	}
	return false
}

type ServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpConfig    *HTTPConfig            `protobuf:"bytes,1,opt,name=http_config,json=httpConfig,proto3,oneof" json:"http_config,omitempty"`
	TcpConfig     *TCPConfig             `protobuf:"bytes,2,opt,name=tcp_config,json=tcpConfig,proto3,oneof" json:"tcp_config,omitempty"`
	GrpcConfig    *GRPCConfig            `protobuf:"bytes,3,opt,name=grpc_config,json=grpcConfig,proto3,oneof" json:"grpc_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_sentinel_service_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_service_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_sentinel_service_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceConfig) GetHttpConfig() *HTTPConfig {
	if x != nil {
		return x.HttpConfig
	}
	return nil
}

func (x *ServiceConfig) GetTcpConfig() *TCPConfig {
	if x != nil {
		return x.TcpConfig
	}
	return nil
}

func (x *ServiceConfig) GetGrpcConfig() *GRPCConfig {
	if x != nil {
		return x.GrpcConfig
	}
	return nil
}

type Service struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol               v1.ServiceProtocol     `protobuf:"varint,3,opt,name=protocol,proto3,enum=sentinel.common.v1.ServiceProtocol" json:"protocol,omitempty"`
	Interval               int64                  `protobuf:"varint,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout                int64                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Retries                int64                  `protobuf:"varint,6,opt,name=retries,proto3" json:"retries,omitempty"`
	Tags                   []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Config                 *ServiceConfig         `protobuf:"bytes,8,opt,name=config,proto3" json:"config,omitempty"`
	IsNotificationsEnabled bool                   `protobuf:"varint,9,opt,name=is_notifications_enabled,json=isNotificationsEnabled,proto3" json:"is_notifications_enabled,omitempty"`
	IsEnabled              bool                   `protobuf:"varint,10,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_sentinel_service_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_service_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_sentinel_service_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetProtocol() v1.ServiceProtocol {
	if x != nil {
		return x.Protocol
	}
	return v1.ServiceProtocol(0)
}

func (x *Service) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *Service) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Service) GetRetries() int64 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *Service) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Service) GetConfig() *ServiceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Service) GetIsNotificationsEnabled() bool {
	if x != nil {
		return x.IsNotificationsEnabled
	}
	return false
}

func (x *Service) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *Service) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Service) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type HTTPConfig_EndpointConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method         string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body           string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ExpectedStatus int32                  `protobuf:"varint,6,opt,name=expected_status,json=expectedStatus,proto3" json:"expected_status,omitempty"`
	JsonPath       string                 `protobuf:"bytes,7,opt,name=json_path,json=jsonPath,proto3" json:"json_path,omitempty"`
	Username       string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Password       string                 `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HTTPConfig_EndpointConfig) Reset() {
	*x = HTTPConfig_EndpointConfig{}
	mi := &file_sentinel_service_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPConfig_EndpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPConfig_EndpointConfig) ProtoMessage() {}

func (x *HTTPConfig_EndpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_service_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPConfig_EndpointConfig.ProtoReflect.Descriptor instead.
func (*HTTPConfig_EndpointConfig) Descriptor() ([]byte, []int) {
	return file_sentinel_service_v1_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HTTPConfig_EndpointConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HTTPConfig_EndpointConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPConfig_EndpointConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPConfig_EndpointConfig) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPConfig_EndpointConfig) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *HTTPConfig_EndpointConfig) GetExpectedStatus() int32 {
	if x != nil {
		return x.ExpectedStatus
	}
	return 0
}

func (x *HTTPConfig_EndpointConfig) GetJsonPath() string {
	if x != nil {
		return x.JsonPath
	}
	return ""
}

func (x *HTTPConfig_EndpointConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *HTTPConfig_EndpointConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_sentinel_service_v1_service_proto protoreflect.FileDescriptor

const file_sentinel_service_v1_service_proto_rawDesc = "" +
	"\n" +
	"!sentinel/service/v1/service.proto\x12\x13sentinel.service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!sentinel/common/v1/protocol.proto\"\xee\x03\n" +
	"\n" +
	"HTTPConfig\x12L\n" +
	"\tendpoints\x18\x01 \x03(\v2..sentinel.service.v1.HTTPConfig.EndpointConfigR\tendpoints\x12\x1c\n" +
	"\tcondition\x18\x02 \x01(\tR\tcondition\x1a\xf3\x02\n" +
	"\x0eEndpointConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12U\n" +
	"\aheaders\x18\x04 \x03(\v2;.sentinel.service.v1.HTTPConfig.EndpointConfig.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12'\n" +
	"\x0fexpected_status\x18\x06 \x01(\x05R\x0eexpectedStatus\x12\x1b\n" +
	"\tjson_path\x18\a \x01(\tR\bjsonPath\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\t \x01(\tR\bpassword\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\tTCPConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tsend_data\x18\x02 \x01(\tR\bsendData\x12\x1f\n" +
	"\vexpect_data\x18\x03 \x01(\tR\n" +
	"expectData\"\x9f\x01\n" +
	"\n" +
	"GRPCConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"check_type\x18\x02 \x01(\tR\tcheckType\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03tls\x18\x04 \x01(\bR\x03tls\x12!\n" +
	"\finsecure_tls\x18\x05 \x01(\bR\vinsecureTls\"\x90\x02\n" +
	"\rServiceConfig\x12E\n" +
	"\vhttp_config\x18\x01 \x01(\v2\x1f.sentinel.service.v1.HTTPConfigH\x00R\n" +
	"httpConfig\x88\x01\x01\x12B\n" +
	"\n" +
	"tcp_config\x18\x02 \x01(\v2\x1e.sentinel.service.v1.TCPConfigH\x01R\ttcpConfig\x88\x01\x01\x12E\n" +
	"\vgrpc_config\x18\x03 \x01(\v2\x1f.sentinel.service.v1.GRPCConfigH\x02R\n" +
	"grpcConfig\x88\x01\x01B\x0e\n" +
	"\f_http_configB\r\n" +
	"\v_tcp_configB\x0e\n" +
	"\f_grpc_config\"\xdd\x03\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12?\n" +
	"\bprotocol\x18\x03 \x01(\x0e2#.sentinel.common.v1.ServiceProtocolR\bprotocol\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\x03R\binterval\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x03R\atimeout\x12\x18\n" +
	"\aretries\x18\x06 \x01(\x03R\aretries\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12:\n" +
	"\x06config\x18\b \x01(\v2\".sentinel.service.v1.ServiceConfigR\x06config\x128\n" +
	"\x18is_notifications_enabled\x18\t \x01(\bR\x16isNotificationsEnabled\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\n" +
	" \x01(\bR\tisEnabled\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\xec\x01\n" +
	"\x17com.sentinel.service.v1B\fServiceProtoP\x01ZUgithub.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/service/v1;servicev1\xa2\x02\x03SSX\xaa\x02\x13Sentinel.Service.V1\xca\x02\x13Sentinel\\Service\\V1\xe2\x02\x1fSentinel\\Service\\V1\\GPBMetadata\xea\x02\x15Sentinel::Service::V1b\x06proto3"

var (
	file_sentinel_service_v1_service_proto_rawDescOnce sync.Once
	file_sentinel_service_v1_service_proto_rawDescData []byte
)

func file_sentinel_service_v1_service_proto_rawDescGZIP() []byte {
	file_sentinel_service_v1_service_proto_rawDescOnce.Do(func() {
		file_sentinel_service_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinel_service_v1_service_proto_rawDesc), len(file_sentinel_service_v1_service_proto_rawDesc)))
	})
	return file_sentinel_service_v1_service_proto_rawDescData
}

var file_sentinel_service_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sentinel_service_v1_service_proto_goTypes = []any{
	(*HTTPConfig)(nil),                // 0: sentinel.service.v1.HTTPConfig
	(*TCPConfig)(nil),                 // 1: sentinel.service.v1.TCPConfig
	(*GRPCConfig)(nil),                // 2: sentinel.service.v1.GRPCConfig
	(*ServiceConfig)(nil),             // 3: sentinel.service.v1.ServiceConfig
	(*Service)(nil),                   // 4: sentinel.service.v1.Service
	(*HTTPConfig_EndpointConfig)(nil), // 5: sentinel.service.v1.HTTPConfig.EndpointConfig
	nil,                               // 6: sentinel.service.v1.HTTPConfig.EndpointConfig.HeadersEntry
	(v1.ServiceProtocol)(0),           // 7: sentinel.common.v1.ServiceProtocol
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_sentinel_service_v1_service_proto_depIdxs = []int32{
	5, // 0: sentinel.service.v1.HTTPConfig.endpoints:type_name -> sentinel.service.v1.HTTPConfig.EndpointConfig
	0, // 1: sentinel.service.v1.ServiceConfig.http_config:type_name -> sentinel.service.v1.HTTPConfig
	1, // 2: sentinel.service.v1.ServiceConfig.tcp_config:type_name -> sentinel.service.v1.TCPConfig
	2, // 3: sentinel.service.v1.ServiceConfig.grpc_config:type_name -> sentinel.service.v1.GRPCConfig
	7, // 4: sentinel.service.v1.Service.protocol:type_name -> sentinel.common.v1.ServiceProtocol
	3, // 5: sentinel.service.v1.Service.config:type_name -> sentinel.service.v1.ServiceConfig
	8, // 6: sentinel.service.v1.Service.created_at:type_name -> google.protobuf.Timestamp
	8, // 7: sentinel.service.v1.Service.updated_at:type_name -> google.protobuf.Timestamp
	6, // 8: sentinel.service.v1.HTTPConfig.EndpointConfig.headers:type_name -> sentinel.service.v1.HTTPConfig.EndpointConfig.HeadersEntry
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_sentinel_service_v1_service_proto_init() }
func file_sentinel_service_v1_service_proto_init() {
	if File_sentinel_service_v1_service_proto != nil {
		return
	}
	file_sentinel_service_v1_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinel_service_v1_service_proto_rawDesc), len(file_sentinel_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sentinel_service_v1_service_proto_goTypes,
		DependencyIndexes: file_sentinel_service_v1_service_proto_depIdxs,
		MessageInfos:      file_sentinel_service_v1_service_proto_msgTypes,
	}.Build()
	File_sentinel_service_v1_service_proto = out.File
	file_sentinel_service_v1_service_proto_goTypes = nil
	file_sentinel_service_v1_service_proto_depIdxs = nil
}
