/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { WebSuccessResponse } from "../../types/model";

import { customFetcher } from ".././baseApi";

export const getUpgrade = () => {
  /**
   * Triggers a manual upgrade of the server
   * @summary Manual upgrade
   */
  const getServerUpgrade = () => {
    return customFetcher<WebSuccessResponse>({
      url: `/server/upgrade`,
      method: "GET",
    });
  };
  return { getServerUpgrade };
};
export type GetServerUpgradeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUpgrade>["getServerUpgrade"]>>
>;
