// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor_states_gen.sql

package repo_monitor_states

import (
	"context"
	"time"

	"github.com/sxwebdev/sentinel/internal/models"
)

const create = `-- name: Create :one
INSERT INTO monitor_states (id, project_id, monitor_id, resource_id, agent_id, severity, status, last_check, last_error, consecutive_fails, consecutive_success, total_checks, avg_response_time)
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	RETURNING id, project_id, monitor_id, resource_id, agent_id, severity, status, last_check, last_error, consecutive_fails, consecutive_success, total_checks, avg_response_time, updated_at
`

type CreateParams struct {
	ID                 string     `db:"id" json:"id"`
	ProjectID          string     `db:"project_id" json:"project_id"`
	MonitorID          string     `db:"monitor_id" json:"monitor_id"`
	ResourceID         string     `db:"resource_id" json:"resource_id"`
	AgentID            *string    `db:"agent_id" json:"agent_id"`
	Severity           int64      `db:"severity" json:"severity"`
	Status             string     `db:"status" json:"status"`
	LastCheck          *time.Time `db:"last_check" json:"last_check"`
	LastError          *string    `db:"last_error" json:"last_error"`
	ConsecutiveFails   int64      `db:"consecutive_fails" json:"consecutive_fails"`
	ConsecutiveSuccess int64      `db:"consecutive_success" json:"consecutive_success"`
	TotalChecks        int64      `db:"total_checks" json:"total_checks"`
	AvgResponseTime    int64      `db:"avg_response_time" json:"avg_response_time"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.MonitorState, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.ProjectID,
		arg.MonitorID,
		arg.ResourceID,
		arg.AgentID,
		arg.Severity,
		arg.Status,
		arg.LastCheck,
		arg.LastError,
		arg.ConsecutiveFails,
		arg.ConsecutiveSuccess,
		arg.TotalChecks,
		arg.AvgResponseTime,
	)
	var i models.MonitorState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MonitorID,
		&i.ResourceID,
		&i.AgentID,
		&i.Severity,
		&i.Status,
		&i.LastCheck,
		&i.LastError,
		&i.ConsecutiveFails,
		&i.ConsecutiveSuccess,
		&i.TotalChecks,
		&i.AvgResponseTime,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM monitor_states WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, project_id, monitor_id, resource_id, agent_id, severity, status, last_check, last_error, consecutive_fails, consecutive_success, total_checks, avg_response_time, updated_at FROM monitor_states
`

func (q *Queries) GetAll(ctx context.Context) ([]*models.MonitorState, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.MonitorState{}
	for rows.Next() {
		var i models.MonitorState
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MonitorID,
			&i.ResourceID,
			&i.AgentID,
			&i.Severity,
			&i.Status,
			&i.LastCheck,
			&i.LastError,
			&i.ConsecutiveFails,
			&i.ConsecutiveSuccess,
			&i.TotalChecks,
			&i.AvgResponseTime,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, project_id, monitor_id, resource_id, agent_id, severity, status, last_check, last_error, consecutive_fails, consecutive_success, total_checks, avg_response_time, updated_at FROM monitor_states WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.MonitorState, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.MonitorState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MonitorID,
		&i.ResourceID,
		&i.AgentID,
		&i.Severity,
		&i.Status,
		&i.LastCheck,
		&i.LastError,
		&i.ConsecutiveFails,
		&i.ConsecutiveSuccess,
		&i.TotalChecks,
		&i.AvgResponseTime,
		&i.UpdatedAt,
	)
	return &i, err
}
