syntax = "proto3";
package sentinel.agent.v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "sentinel/common/v1/info.proto";
import "sentinel/common/v1/status.proto";
import "sentinel/service/v1/service.proto";

// AgentService is the service for agent management
service AgentService {
  // Ping is a health check endpoint.
  rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty);
  // Authenticate authenticates the agent and returns an authentication token.
  rpc Authenticate(AuthenticateRequest) returns (AuthenticateResponse);
  // ReportSystemInfo reports the system information of the agent.
  rpc ReportSystemInfo(ReportSystemInfoRequest)
      returns (ReportSystemInfoResponse) {}
  // FetchServices fetches the list of services to be monitored by the agent.
  rpc FetchServices(FetchServicesRequest) returns (FetchServicesResponse);
  // SubscribeServices subscribes to the service updates.
  rpc SubscribeServices(SubscribeServicesRequest)
      returns (stream SubscribeServicesResponse);
  // StreamChecks streams the check results to the server.
  rpc StreamChecks(stream StreamChecksRequest)
      returns (stream StreamChecksResponse);
}

enum AgentStatus {
  AGENT_STATUS_UNSPECIFIED = 0;
  AGENT_STATUS_ACTIVE = 1;
  AGENT_STATUS_INACTIVE = 2;
}

message ServiceUpsert {
  string rev = 1;
  service.v1.Service service = 2;
}

message ServiceDelete {
  string rev = 1;
  string service_id = 2;
}

message AuthenticateRequest { string fingerprint = 1; }
message AuthenticateResponse {}

message ReportSystemInfoRequest {
  AgentStatus status = 1;
  common.v1.SystemInfo system_info = 2;
}
message ReportSystemInfoResponse {}

message FetchServicesRequest {}
message FetchServicesResponse { repeated service.v1.Service services = 1; }

message SubscribeServicesRequest { string last_rev = 1; }
message SubscribeServicesResponse {
  oneof update {
    ServiceUpsert upsert = 1;
    ServiceDelete delete = 2;
  }
}

message CheckResult {
  string service_id = 1;
  common.v1.ServiceStatus status = 2;
  google.protobuf.Timestamp checked_at = 3;
  string message = 4;
  int64 response_time = 5;
}

message StreamChecksRequest {
  uint64 seq = 1;
  repeated CheckResult results = 2;
}
message StreamChecksResponse { uint64 upto_seq = 1; }
