// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.12
package repo_projects

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameProjects TableName = "projects"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameProjectsId          ColumnName = "id"
	ColumnNameProjectsName        ColumnName = "name"
	ColumnNameProjectsDescription ColumnName = "description"
	ColumnNameProjectsSettings    ColumnName = "settings"
	ColumnNameProjectsCreatedAt   ColumnName = "created_at"
	ColumnNameProjectsUpdatedAt   ColumnName = "updated_at"
)

func ProjectsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameProjectsId,
		ColumnNameProjectsName,
		ColumnNameProjectsDescription,
		ColumnNameProjectsSettings,
		ColumnNameProjectsCreatedAt,
		ColumnNameProjectsUpdatedAt,
	}
}
