// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects_gen.sql

package repo_projects

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

const create = `-- name: Create :one
INSERT INTO projects (id, name, description, settings)
	VALUES (?, ?, ?, ?)
	RETURNING id, name, description, settings, created_at, updated_at
`

type CreateParams struct {
	ID          string                 `db:"id" json:"id" validate:"required"`
	Name        string                 `db:"name" json:"name" validate:"required"`
	Description string                 `db:"description" json:"description"`
	Settings    models.ProjectSettings `db:"settings" json:"settings"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Project, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Settings,
	)
	var i models.Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM projects WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, name, description, settings, created_at, updated_at FROM projects
`

func (q *Queries) GetAll(ctx context.Context) ([]*models.Project, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Project{}
	for rows.Next() {
		var i models.Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, name, description, settings, created_at, updated_at FROM projects WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Project, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const update = `-- name: Update :one
UPDATE projects
	SET name=?, description=?, settings=?, updated_at=CURRENT_TIMESTAMP
	WHERE id=?
	RETURNING id, name, description, settings, created_at, updated_at
`

type UpdateParams struct {
	Name        string                 `db:"name" json:"name" validate:"required"`
	Description string                 `db:"description" json:"description"`
	Settings    models.ProjectSettings `db:"settings" json:"settings"`
	ID          string                 `db:"id" json:"id" validate:"required"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.Project, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.Name,
		arg.Description,
		arg.Settings,
		arg.ID,
	)
	var i models.Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
