// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts_gen.sql

package repo_alerts

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

const create = `-- name: Create :one
INSERT INTO alerts (id, incident_id, policy_id, status)
	VALUES (?, ?, ?, ?)
	RETURNING id, incident_id, policy_id, status, created_at
`

type CreateParams struct {
	ID         string `db:"id" json:"id"`
	IncidentID string `db:"incident_id" json:"incident_id"`
	PolicyID   string `db:"policy_id" json:"policy_id"`
	Status     string `db:"status" json:"status"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Alert, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.IncidentID,
		arg.PolicyID,
		arg.Status,
	)
	var i models.Alert
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.PolicyID,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM alerts WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, incident_id, policy_id, status, created_at FROM alerts
`

func (q *Queries) GetAll(ctx context.Context) ([]*models.Alert, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Alert{}
	for rows.Next() {
		var i models.Alert
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.PolicyID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, incident_id, policy_id, status, created_at FROM alerts WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Alert, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Alert
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.PolicyID,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}
