// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.12
package repo_alerts

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameAlerts TableName = "alerts"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameAlertsId         ColumnName = "id"
	ColumnNameAlertsIncidentId ColumnName = "incident_id"
	ColumnNameAlertsPolicyId   ColumnName = "policy_id"
	ColumnNameAlertsStatus     ColumnName = "status"
	ColumnNameAlertsCreatedAt  ColumnName = "created_at"
)

func AlertsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameAlertsId,
		ColumnNameAlertsIncidentId,
		ColumnNameAlertsPolicyId,
		ColumnNameAlertsStatus,
		ColumnNameAlertsCreatedAt,
	}
}
