/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type {
  GetTagsCount200
} from '../../types/model';

import { customFetcher } from '.././baseApi';



  export const getTags = () => {
/**
 * Retrieves all unique tags used across services
 * @summary Get all tags
 */
const getTags = (
    
 ) => {
      return customFetcher<string[]>(
      {url: `/tags`, method: 'GET'
    },
      );
    }
  /**
 * Retrieves all unique tags along with their usage count across services
 * @summary Get all tags with usage count
 */
const getTagsCount = (
    
 ) => {
      return customFetcher<GetTagsCount200>(
      {url: `/tags/count`, method: 'GET'
    },
      );
    }
  return {getTags,getTagsCount}};
export type GetTagsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTags>['getTags']>>>
export type GetTagsCountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTags>['getTagsCount']>>>
