// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: sentinel/hub/v1/hub.proto

package hubv1

import (
	v11 "github.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/agents/v1"
	v1 "github.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/service/v1"
	v12 "github.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/system/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceUpsert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rev           string                 `protobuf:"bytes,1,opt,name=rev,proto3" json:"rev,omitempty"`
	Service       *v1.Service            `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUpsert) Reset() {
	*x = ServiceUpsert{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpsert) ProtoMessage() {}

func (x *ServiceUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpsert.ProtoReflect.Descriptor instead.
func (*ServiceUpsert) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceUpsert) GetRev() string {
	if x != nil {
		return x.Rev
	}
	return ""
}

func (x *ServiceUpsert) GetService() *v1.Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type ServiceDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rev           string                 `protobuf:"bytes,1,opt,name=rev,proto3" json:"rev,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDelete) Reset() {
	*x = ServiceDelete{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDelete) ProtoMessage() {}

func (x *ServiceDelete) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDelete.ProtoReflect.Descriptor instead.
func (*ServiceDelete) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceDelete) GetRev() string {
	if x != nil {
		return x.Rev
	}
	return ""
}

func (x *ServiceDelete) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{3}
}

type ReportSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        v11.AgentStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=sentinel.agents.v1.AgentStatus" json:"status,omitempty"`
	SystemInfo    *v12.SystemInfo        `protobuf:"bytes,2,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSystemInfoRequest) Reset() {
	*x = ReportSystemInfoRequest{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSystemInfoRequest) ProtoMessage() {}

func (x *ReportSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*ReportSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{4}
}

func (x *ReportSystemInfoRequest) GetStatus() v11.AgentStatus {
	if x != nil {
		return x.Status
	}
	return v11.AgentStatus(0)
}

func (x *ReportSystemInfoRequest) GetSystemInfo() *v12.SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

type ReportSystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSystemInfoResponse) Reset() {
	*x = ReportSystemInfoResponse{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSystemInfoResponse) ProtoMessage() {}

func (x *ReportSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*ReportSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{5}
}

type FetchServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchServicesRequest) Reset() {
	*x = FetchServicesRequest{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchServicesRequest) ProtoMessage() {}

func (x *FetchServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchServicesRequest.ProtoReflect.Descriptor instead.
func (*FetchServicesRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{6}
}

type FetchServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*v1.Service          `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchServicesResponse) Reset() {
	*x = FetchServicesResponse{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchServicesResponse) ProtoMessage() {}

func (x *FetchServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchServicesResponse.ProtoReflect.Descriptor instead.
func (*FetchServicesResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{7}
}

func (x *FetchServicesResponse) GetServices() []*v1.Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type SubscribeServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastRev       string                 `protobuf:"bytes,1,opt,name=last_rev,json=lastRev,proto3" json:"last_rev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServicesRequest) Reset() {
	*x = SubscribeServicesRequest{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServicesRequest) ProtoMessage() {}

func (x *SubscribeServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServicesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeServicesRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeServicesRequest) GetLastRev() string {
	if x != nil {
		return x.LastRev
	}
	return ""
}

type SubscribeServicesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*SubscribeServicesResponse_Upsert
	//	*SubscribeServicesResponse_Delete
	Update        isSubscribeServicesResponse_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServicesResponse) Reset() {
	*x = SubscribeServicesResponse{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServicesResponse) ProtoMessage() {}

func (x *SubscribeServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServicesResponse.ProtoReflect.Descriptor instead.
func (*SubscribeServicesResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeServicesResponse) GetUpdate() isSubscribeServicesResponse_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *SubscribeServicesResponse) GetUpsert() *ServiceUpsert {
	if x != nil {
		if x, ok := x.Update.(*SubscribeServicesResponse_Upsert); ok {
			return x.Upsert
		}
	}
	return nil
}

func (x *SubscribeServicesResponse) GetDelete() *ServiceDelete {
	if x != nil {
		if x, ok := x.Update.(*SubscribeServicesResponse_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isSubscribeServicesResponse_Update interface {
	isSubscribeServicesResponse_Update()
}

type SubscribeServicesResponse_Upsert struct {
	Upsert *ServiceUpsert `protobuf:"bytes,1,opt,name=upsert,proto3,oneof"`
}

type SubscribeServicesResponse_Delete struct {
	Delete *ServiceDelete `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

func (*SubscribeServicesResponse_Upsert) isSubscribeServicesResponse_Update() {}

func (*SubscribeServicesResponse_Delete) isSubscribeServicesResponse_Update() {}

type CheckResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServiceId            string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Status               v1.ServiceStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=sentinel.service.v1.ServiceStatus" json:"status,omitempty"`
	CheckedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	ResponseMessage      string                 `protobuf:"bytes,4,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	ResponseErrorMessage string                 `protobuf:"bytes,5,opt,name=response_error_message,json=responseErrorMessage,proto3" json:"response_error_message,omitempty"`
	ResponseTime         int64                  `protobuf:"varint,6,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{10}
}

func (x *CheckResult) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CheckResult) GetStatus() v1.ServiceStatus {
	if x != nil {
		return x.Status
	}
	return v1.ServiceStatus(0)
}

func (x *CheckResult) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

func (x *CheckResult) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *CheckResult) GetResponseErrorMessage() string {
	if x != nil {
		return x.ResponseErrorMessage
	}
	return ""
}

func (x *CheckResult) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

type StreamChecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Results       []*CheckResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChecksRequest) Reset() {
	*x = StreamChecksRequest{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChecksRequest) ProtoMessage() {}

func (x *StreamChecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChecksRequest.ProtoReflect.Descriptor instead.
func (*StreamChecksRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{11}
}

func (x *StreamChecksRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StreamChecksRequest) GetResults() []*CheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type StreamChecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UptoSeq       uint64                 `protobuf:"varint,1,opt,name=upto_seq,json=uptoSeq,proto3" json:"upto_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChecksResponse) Reset() {
	*x = StreamChecksResponse{}
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChecksResponse) ProtoMessage() {}

func (x *StreamChecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_hub_v1_hub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChecksResponse.ProtoReflect.Descriptor instead.
func (*StreamChecksResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_hub_v1_hub_proto_rawDescGZIP(), []int{12}
}

func (x *StreamChecksResponse) GetUptoSeq() uint64 {
	if x != nil {
		return x.UptoSeq
	}
	return 0
}

var File_sentinel_hub_v1_hub_proto protoreflect.FileDescriptor

const file_sentinel_hub_v1_hub_proto_rawDesc = "" +
	"\n" +
	"\x19sentinel/hub/v1/hub.proto\x12\x0fsentinel.hub.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a sentinel/system/v1/service.proto\x1a!sentinel/service/v1/service.proto\x1a\x1fsentinel/agents/v1/agents.proto\"Y\n" +
	"\rServiceUpsert\x12\x10\n" +
	"\x03rev\x18\x01 \x01(\tR\x03rev\x126\n" +
	"\aservice\x18\x02 \x01(\v2\x1c.sentinel.service.v1.ServiceR\aservice\"@\n" +
	"\rServiceDelete\x12\x10\n" +
	"\x03rev\x18\x01 \x01(\tR\x03rev\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"7\n" +
	"\x13AuthenticateRequest\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\"\x16\n" +
	"\x14AuthenticateResponse\"\x93\x01\n" +
	"\x17ReportSystemInfoRequest\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.sentinel.agents.v1.AgentStatusR\x06status\x12?\n" +
	"\vsystem_info\x18\x02 \x01(\v2\x1e.sentinel.system.v1.SystemInfoR\n" +
	"systemInfo\"\x1a\n" +
	"\x18ReportSystemInfoResponse\"\x16\n" +
	"\x14FetchServicesRequest\"Q\n" +
	"\x15FetchServicesResponse\x128\n" +
	"\bservices\x18\x01 \x03(\v2\x1c.sentinel.service.v1.ServiceR\bservices\"5\n" +
	"\x18SubscribeServicesRequest\x12\x19\n" +
	"\blast_rev\x18\x01 \x01(\tR\alastRev\"\x99\x01\n" +
	"\x19SubscribeServicesResponse\x128\n" +
	"\x06upsert\x18\x01 \x01(\v2\x1e.sentinel.hub.v1.ServiceUpsertH\x00R\x06upsert\x128\n" +
	"\x06delete\x18\x02 \x01(\v2\x1e.sentinel.hub.v1.ServiceDeleteH\x00R\x06deleteB\b\n" +
	"\x06update\"\xa9\x02\n" +
	"\vCheckResult\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".sentinel.service.v1.ServiceStatusR\x06status\x129\n" +
	"\n" +
	"checked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\x12)\n" +
	"\x10response_message\x18\x04 \x01(\tR\x0fresponseMessage\x124\n" +
	"\x16response_error_message\x18\x05 \x01(\tR\x14responseErrorMessage\x12#\n" +
	"\rresponse_time\x18\x06 \x01(\x03R\fresponseTime\"_\n" +
	"\x13StreamChecksRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x126\n" +
	"\aresults\x18\x02 \x03(\v2\x1c.sentinel.hub.v1.CheckResultR\aresults\"1\n" +
	"\x14StreamChecksResponse\x12\x19\n" +
	"\bupto_seq\x18\x01 \x01(\x04R\auptoSeq2\xbb\x04\n" +
	"\n" +
	"HubService\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\fAuthenticate\x12$.sentinel.hub.v1.AuthenticateRequest\x1a%.sentinel.hub.v1.AuthenticateResponse\x12i\n" +
	"\x10ReportSystemInfo\x12(.sentinel.hub.v1.ReportSystemInfoRequest\x1a).sentinel.hub.v1.ReportSystemInfoResponse\"\x00\x12^\n" +
	"\rFetchServices\x12%.sentinel.hub.v1.FetchServicesRequest\x1a&.sentinel.hub.v1.FetchServicesResponse\x12l\n" +
	"\x11SubscribeServices\x12).sentinel.hub.v1.SubscribeServicesRequest\x1a*.sentinel.hub.v1.SubscribeServicesResponse0\x01\x12_\n" +
	"\fStreamChecks\x12$.sentinel.hub.v1.StreamChecksRequest\x1a%.sentinel.hub.v1.StreamChecksResponse(\x010\x01B\xcc\x01\n" +
	"\x13com.sentinel.hub.v1B\bHubProtoP\x01ZMgithub.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/hub/v1;hubv1\xa2\x02\x03SHX\xaa\x02\x0fSentinel.Hub.V1\xca\x02\x0fSentinel\\Hub\\V1\xe2\x02\x1bSentinel\\Hub\\V1\\GPBMetadata\xea\x02\x11Sentinel::Hub::V1b\x06proto3"

var (
	file_sentinel_hub_v1_hub_proto_rawDescOnce sync.Once
	file_sentinel_hub_v1_hub_proto_rawDescData []byte
)

func file_sentinel_hub_v1_hub_proto_rawDescGZIP() []byte {
	file_sentinel_hub_v1_hub_proto_rawDescOnce.Do(func() {
		file_sentinel_hub_v1_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinel_hub_v1_hub_proto_rawDesc), len(file_sentinel_hub_v1_hub_proto_rawDesc)))
	})
	return file_sentinel_hub_v1_hub_proto_rawDescData
}

var file_sentinel_hub_v1_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_sentinel_hub_v1_hub_proto_goTypes = []any{
	(*ServiceUpsert)(nil),             // 0: sentinel.hub.v1.ServiceUpsert
	(*ServiceDelete)(nil),             // 1: sentinel.hub.v1.ServiceDelete
	(*AuthenticateRequest)(nil),       // 2: sentinel.hub.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),      // 3: sentinel.hub.v1.AuthenticateResponse
	(*ReportSystemInfoRequest)(nil),   // 4: sentinel.hub.v1.ReportSystemInfoRequest
	(*ReportSystemInfoResponse)(nil),  // 5: sentinel.hub.v1.ReportSystemInfoResponse
	(*FetchServicesRequest)(nil),      // 6: sentinel.hub.v1.FetchServicesRequest
	(*FetchServicesResponse)(nil),     // 7: sentinel.hub.v1.FetchServicesResponse
	(*SubscribeServicesRequest)(nil),  // 8: sentinel.hub.v1.SubscribeServicesRequest
	(*SubscribeServicesResponse)(nil), // 9: sentinel.hub.v1.SubscribeServicesResponse
	(*CheckResult)(nil),               // 10: sentinel.hub.v1.CheckResult
	(*StreamChecksRequest)(nil),       // 11: sentinel.hub.v1.StreamChecksRequest
	(*StreamChecksResponse)(nil),      // 12: sentinel.hub.v1.StreamChecksResponse
	(*v1.Service)(nil),                // 13: sentinel.service.v1.Service
	(v11.AgentStatus)(0),              // 14: sentinel.agents.v1.AgentStatus
	(*v12.SystemInfo)(nil),            // 15: sentinel.system.v1.SystemInfo
	(v1.ServiceStatus)(0),             // 16: sentinel.service.v1.ServiceStatus
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 18: google.protobuf.Empty
}
var file_sentinel_hub_v1_hub_proto_depIdxs = []int32{
	13, // 0: sentinel.hub.v1.ServiceUpsert.service:type_name -> sentinel.service.v1.Service
	14, // 1: sentinel.hub.v1.ReportSystemInfoRequest.status:type_name -> sentinel.agents.v1.AgentStatus
	15, // 2: sentinel.hub.v1.ReportSystemInfoRequest.system_info:type_name -> sentinel.system.v1.SystemInfo
	13, // 3: sentinel.hub.v1.FetchServicesResponse.services:type_name -> sentinel.service.v1.Service
	0,  // 4: sentinel.hub.v1.SubscribeServicesResponse.upsert:type_name -> sentinel.hub.v1.ServiceUpsert
	1,  // 5: sentinel.hub.v1.SubscribeServicesResponse.delete:type_name -> sentinel.hub.v1.ServiceDelete
	16, // 6: sentinel.hub.v1.CheckResult.status:type_name -> sentinel.service.v1.ServiceStatus
	17, // 7: sentinel.hub.v1.CheckResult.checked_at:type_name -> google.protobuf.Timestamp
	10, // 8: sentinel.hub.v1.StreamChecksRequest.results:type_name -> sentinel.hub.v1.CheckResult
	18, // 9: sentinel.hub.v1.HubService.Ping:input_type -> google.protobuf.Empty
	2,  // 10: sentinel.hub.v1.HubService.Authenticate:input_type -> sentinel.hub.v1.AuthenticateRequest
	4,  // 11: sentinel.hub.v1.HubService.ReportSystemInfo:input_type -> sentinel.hub.v1.ReportSystemInfoRequest
	6,  // 12: sentinel.hub.v1.HubService.FetchServices:input_type -> sentinel.hub.v1.FetchServicesRequest
	8,  // 13: sentinel.hub.v1.HubService.SubscribeServices:input_type -> sentinel.hub.v1.SubscribeServicesRequest
	11, // 14: sentinel.hub.v1.HubService.StreamChecks:input_type -> sentinel.hub.v1.StreamChecksRequest
	18, // 15: sentinel.hub.v1.HubService.Ping:output_type -> google.protobuf.Empty
	3,  // 16: sentinel.hub.v1.HubService.Authenticate:output_type -> sentinel.hub.v1.AuthenticateResponse
	5,  // 17: sentinel.hub.v1.HubService.ReportSystemInfo:output_type -> sentinel.hub.v1.ReportSystemInfoResponse
	7,  // 18: sentinel.hub.v1.HubService.FetchServices:output_type -> sentinel.hub.v1.FetchServicesResponse
	9,  // 19: sentinel.hub.v1.HubService.SubscribeServices:output_type -> sentinel.hub.v1.SubscribeServicesResponse
	12, // 20: sentinel.hub.v1.HubService.StreamChecks:output_type -> sentinel.hub.v1.StreamChecksResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_sentinel_hub_v1_hub_proto_init() }
func file_sentinel_hub_v1_hub_proto_init() {
	if File_sentinel_hub_v1_hub_proto != nil {
		return
	}
	file_sentinel_hub_v1_hub_proto_msgTypes[9].OneofWrappers = []any{
		(*SubscribeServicesResponse_Upsert)(nil),
		(*SubscribeServicesResponse_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinel_hub_v1_hub_proto_rawDesc), len(file_sentinel_hub_v1_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentinel_hub_v1_hub_proto_goTypes,
		DependencyIndexes: file_sentinel_hub_v1_hub_proto_depIdxs,
		MessageInfos:      file_sentinel_hub_v1_hub_proto_msgTypes,
	}.Build()
	File_sentinel_hub_v1_hub_proto = out.File
	file_sentinel_hub_v1_hub_proto_goTypes = nil
	file_sentinel_hub_v1_hub_proto_depIdxs = nil
}
