// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sentinel/projects/v1/projects.proto

package projectsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/projects/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProjectsServiceName is the fully-qualified name of the ProjectsService service.
	ProjectsServiceName = "sentinel.projects.v1.ProjectsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProjectsServiceProjectsListProcedure is the fully-qualified name of the ProjectsService's
	// ProjectsList RPC.
	ProjectsServiceProjectsListProcedure = "/sentinel.projects.v1.ProjectsService/ProjectsList"
	// ProjectsServiceProjectCreateProcedure is the fully-qualified name of the ProjectsService's
	// ProjectCreate RPC.
	ProjectsServiceProjectCreateProcedure = "/sentinel.projects.v1.ProjectsService/ProjectCreate"
	// ProjectsServiceProjectGetProcedure is the fully-qualified name of the ProjectsService's
	// ProjectGet RPC.
	ProjectsServiceProjectGetProcedure = "/sentinel.projects.v1.ProjectsService/ProjectGet"
	// ProjectsServiceProjectUpdateProcedure is the fully-qualified name of the ProjectsService's
	// ProjectUpdate RPC.
	ProjectsServiceProjectUpdateProcedure = "/sentinel.projects.v1.ProjectsService/ProjectUpdate"
	// ProjectsServiceProjectDeleteProcedure is the fully-qualified name of the ProjectsService's
	// ProjectDelete RPC.
	ProjectsServiceProjectDeleteProcedure = "/sentinel.projects.v1.ProjectsService/ProjectDelete"
)

// ProjectsServiceClient is a client for the sentinel.projects.v1.ProjectsService service.
type ProjectsServiceClient interface {
	ProjectsList(context.Context, *connect.Request[v1.ProjectsListRequest]) (*connect.Response[v1.ProjectsListResponse], error)
	ProjectCreate(context.Context, *connect.Request[v1.ProjectCreateRequest]) (*connect.Response[v1.ProjectCreateResponse], error)
	ProjectGet(context.Context, *connect.Request[v1.ProjectGetRequest]) (*connect.Response[v1.ProjectGetResponse], error)
	ProjectUpdate(context.Context, *connect.Request[v1.ProjectUpdateRequest]) (*connect.Response[v1.ProjectUpdateResponse], error)
	ProjectDelete(context.Context, *connect.Request[v1.ProjectDeleteRequest]) (*connect.Response[v1.ProjectDeleteResponse], error)
}

// NewProjectsServiceClient constructs a client for the sentinel.projects.v1.ProjectsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectsServiceMethods := v1.File_sentinel_projects_v1_projects_proto.Services().ByName("ProjectsService").Methods()
	return &projectsServiceClient{
		projectsList: connect.NewClient[v1.ProjectsListRequest, v1.ProjectsListResponse](
			httpClient,
			baseURL+ProjectsServiceProjectsListProcedure,
			connect.WithSchema(projectsServiceMethods.ByName("ProjectsList")),
			connect.WithClientOptions(opts...),
		),
		projectCreate: connect.NewClient[v1.ProjectCreateRequest, v1.ProjectCreateResponse](
			httpClient,
			baseURL+ProjectsServiceProjectCreateProcedure,
			connect.WithSchema(projectsServiceMethods.ByName("ProjectCreate")),
			connect.WithClientOptions(opts...),
		),
		projectGet: connect.NewClient[v1.ProjectGetRequest, v1.ProjectGetResponse](
			httpClient,
			baseURL+ProjectsServiceProjectGetProcedure,
			connect.WithSchema(projectsServiceMethods.ByName("ProjectGet")),
			connect.WithClientOptions(opts...),
		),
		projectUpdate: connect.NewClient[v1.ProjectUpdateRequest, v1.ProjectUpdateResponse](
			httpClient,
			baseURL+ProjectsServiceProjectUpdateProcedure,
			connect.WithSchema(projectsServiceMethods.ByName("ProjectUpdate")),
			connect.WithClientOptions(opts...),
		),
		projectDelete: connect.NewClient[v1.ProjectDeleteRequest, v1.ProjectDeleteResponse](
			httpClient,
			baseURL+ProjectsServiceProjectDeleteProcedure,
			connect.WithSchema(projectsServiceMethods.ByName("ProjectDelete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectsServiceClient implements ProjectsServiceClient.
type projectsServiceClient struct {
	projectsList  *connect.Client[v1.ProjectsListRequest, v1.ProjectsListResponse]
	projectCreate *connect.Client[v1.ProjectCreateRequest, v1.ProjectCreateResponse]
	projectGet    *connect.Client[v1.ProjectGetRequest, v1.ProjectGetResponse]
	projectUpdate *connect.Client[v1.ProjectUpdateRequest, v1.ProjectUpdateResponse]
	projectDelete *connect.Client[v1.ProjectDeleteRequest, v1.ProjectDeleteResponse]
}

// ProjectsList calls sentinel.projects.v1.ProjectsService.ProjectsList.
func (c *projectsServiceClient) ProjectsList(ctx context.Context, req *connect.Request[v1.ProjectsListRequest]) (*connect.Response[v1.ProjectsListResponse], error) {
	return c.projectsList.CallUnary(ctx, req)
}

// ProjectCreate calls sentinel.projects.v1.ProjectsService.ProjectCreate.
func (c *projectsServiceClient) ProjectCreate(ctx context.Context, req *connect.Request[v1.ProjectCreateRequest]) (*connect.Response[v1.ProjectCreateResponse], error) {
	return c.projectCreate.CallUnary(ctx, req)
}

// ProjectGet calls sentinel.projects.v1.ProjectsService.ProjectGet.
func (c *projectsServiceClient) ProjectGet(ctx context.Context, req *connect.Request[v1.ProjectGetRequest]) (*connect.Response[v1.ProjectGetResponse], error) {
	return c.projectGet.CallUnary(ctx, req)
}

// ProjectUpdate calls sentinel.projects.v1.ProjectsService.ProjectUpdate.
func (c *projectsServiceClient) ProjectUpdate(ctx context.Context, req *connect.Request[v1.ProjectUpdateRequest]) (*connect.Response[v1.ProjectUpdateResponse], error) {
	return c.projectUpdate.CallUnary(ctx, req)
}

// ProjectDelete calls sentinel.projects.v1.ProjectsService.ProjectDelete.
func (c *projectsServiceClient) ProjectDelete(ctx context.Context, req *connect.Request[v1.ProjectDeleteRequest]) (*connect.Response[v1.ProjectDeleteResponse], error) {
	return c.projectDelete.CallUnary(ctx, req)
}

// ProjectsServiceHandler is an implementation of the sentinel.projects.v1.ProjectsService service.
type ProjectsServiceHandler interface {
	ProjectsList(context.Context, *connect.Request[v1.ProjectsListRequest]) (*connect.Response[v1.ProjectsListResponse], error)
	ProjectCreate(context.Context, *connect.Request[v1.ProjectCreateRequest]) (*connect.Response[v1.ProjectCreateResponse], error)
	ProjectGet(context.Context, *connect.Request[v1.ProjectGetRequest]) (*connect.Response[v1.ProjectGetResponse], error)
	ProjectUpdate(context.Context, *connect.Request[v1.ProjectUpdateRequest]) (*connect.Response[v1.ProjectUpdateResponse], error)
	ProjectDelete(context.Context, *connect.Request[v1.ProjectDeleteRequest]) (*connect.Response[v1.ProjectDeleteResponse], error)
}

// NewProjectsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectsServiceHandler(svc ProjectsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectsServiceMethods := v1.File_sentinel_projects_v1_projects_proto.Services().ByName("ProjectsService").Methods()
	projectsServiceProjectsListHandler := connect.NewUnaryHandler(
		ProjectsServiceProjectsListProcedure,
		svc.ProjectsList,
		connect.WithSchema(projectsServiceMethods.ByName("ProjectsList")),
		connect.WithHandlerOptions(opts...),
	)
	projectsServiceProjectCreateHandler := connect.NewUnaryHandler(
		ProjectsServiceProjectCreateProcedure,
		svc.ProjectCreate,
		connect.WithSchema(projectsServiceMethods.ByName("ProjectCreate")),
		connect.WithHandlerOptions(opts...),
	)
	projectsServiceProjectGetHandler := connect.NewUnaryHandler(
		ProjectsServiceProjectGetProcedure,
		svc.ProjectGet,
		connect.WithSchema(projectsServiceMethods.ByName("ProjectGet")),
		connect.WithHandlerOptions(opts...),
	)
	projectsServiceProjectUpdateHandler := connect.NewUnaryHandler(
		ProjectsServiceProjectUpdateProcedure,
		svc.ProjectUpdate,
		connect.WithSchema(projectsServiceMethods.ByName("ProjectUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	projectsServiceProjectDeleteHandler := connect.NewUnaryHandler(
		ProjectsServiceProjectDeleteProcedure,
		svc.ProjectDelete,
		connect.WithSchema(projectsServiceMethods.ByName("ProjectDelete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sentinel.projects.v1.ProjectsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectsServiceProjectsListProcedure:
			projectsServiceProjectsListHandler.ServeHTTP(w, r)
		case ProjectsServiceProjectCreateProcedure:
			projectsServiceProjectCreateHandler.ServeHTTP(w, r)
		case ProjectsServiceProjectGetProcedure:
			projectsServiceProjectGetHandler.ServeHTTP(w, r)
		case ProjectsServiceProjectUpdateProcedure:
			projectsServiceProjectUpdateHandler.ServeHTTP(w, r)
		case ProjectsServiceProjectDeleteProcedure:
			projectsServiceProjectDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectsServiceHandler struct{}

func (UnimplementedProjectsServiceHandler) ProjectsList(context.Context, *connect.Request[v1.ProjectsListRequest]) (*connect.Response[v1.ProjectsListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.projects.v1.ProjectsService.ProjectsList is not implemented"))
}

func (UnimplementedProjectsServiceHandler) ProjectCreate(context.Context, *connect.Request[v1.ProjectCreateRequest]) (*connect.Response[v1.ProjectCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.projects.v1.ProjectsService.ProjectCreate is not implemented"))
}

func (UnimplementedProjectsServiceHandler) ProjectGet(context.Context, *connect.Request[v1.ProjectGetRequest]) (*connect.Response[v1.ProjectGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.projects.v1.ProjectsService.ProjectGet is not implemented"))
}

func (UnimplementedProjectsServiceHandler) ProjectUpdate(context.Context, *connect.Request[v1.ProjectUpdateRequest]) (*connect.Response[v1.ProjectUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.projects.v1.ProjectsService.ProjectUpdate is not implemented"))
}

func (UnimplementedProjectsServiceHandler) ProjectDelete(context.Context, *connect.Request[v1.ProjectDeleteRequest]) (*connect.Response[v1.ProjectDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sentinel.projects.v1.ProjectsService.ProjectDelete is not implemented"))
}
