// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_policies_gen.sql

package repo_alert_policies

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
	"github.com/sxwebdev/sentinel/internal/store/storecmn"
)

const create = `-- name: Create :one
INSERT INTO alert_policies (id, name, rules, is_enabled, project_id)
	VALUES (?, ?, ?, ?, ?)
	RETURNING id, name, rules, is_enabled, project_id, created_at, updated_at
`

type CreateParams struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Rules     storecmn.JSONField `db:"rules" json:"rules"`
	IsEnabled bool               `db:"is_enabled" json:"is_enabled"`
	ProjectID string             `db:"project_id" json:"project_id"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.AlertPolicy, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Name,
		arg.Rules,
		arg.IsEnabled,
		arg.ProjectID,
	)
	var i models.AlertPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rules,
		&i.IsEnabled,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM alert_policies WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, name, rules, is_enabled, project_id, created_at, updated_at FROM alert_policies
`

func (q *Queries) GetAll(ctx context.Context) ([]*models.AlertPolicy, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.AlertPolicy{}
	for rows.Next() {
		var i models.AlertPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rules,
			&i.IsEnabled,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, name, rules, is_enabled, project_id, created_at, updated_at FROM alert_policies WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.AlertPolicy, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.AlertPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rules,
		&i.IsEnabled,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
