// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.13
package repo_alert_policies

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameAlertPolicies TableName = "alert_policies"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameAlertPoliciesId        ColumnName = "id"
	ColumnNameAlertPoliciesName      ColumnName = "name"
	ColumnNameAlertPoliciesRules     ColumnName = "rules"
	ColumnNameAlertPoliciesIsEnabled ColumnName = "is_enabled"
	ColumnNameAlertPoliciesProjectId ColumnName = "project_id"
	ColumnNameAlertPoliciesCreatedAt ColumnName = "created_at"
	ColumnNameAlertPoliciesUpdatedAt ColumnName = "updated_at"
)

func AlertPoliciesColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameAlertPoliciesId,
		ColumnNameAlertPoliciesName,
		ColumnNameAlertPoliciesRules,
		ColumnNameAlertPoliciesIsEnabled,
		ColumnNameAlertPoliciesProjectId,
		ColumnNameAlertPoliciesCreatedAt,
		ColumnNameAlertPoliciesUpdatedAt,
	}
}
