/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { WebServerInfoResponse } from "../../types/model";

import { customFetcher } from ".././baseApi";

export const getInfo = () => {
  /**
   * Returns basic information about the server
   * @summary Get server info
   */
  const getServerInfo = () => {
    return customFetcher<WebServerInfoResponse>({
      url: `/server/info`,
      method: "GET",
    });
  };
  return { getServerInfo };
};
export type GetServerInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getInfo>["getServerInfo"]>>
>;
