/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sentinel Monitoring API
 * API for service monitoring and incident management
 * OpenAPI spec version: 1.0
 */
import type { WebServerInfoResponse } from "../../types/model";

import { customFetcher } from ".././baseApi";

export const getInfo = () => {
  /**
   * Returns basic information about the server
   * @summary Get server info
   */
  const getInfo = () => {
    return customFetcher<WebServerInfoResponse>({
      url: `/info`,
      method: "GET",
    });
  };
  return { getInfo };
};
export type GetInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getInfo>["getInfo"]>>
>;
