// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: sentinel/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindRequestCommon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *uint32                `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *uint32                `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	OrderBy       *string                `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	IsAscOrder    bool                   `protobuf:"varint,4,opt,name=is_asc_order,json=isAscOrder,proto3" json:"is_asc_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequestCommon) Reset() {
	*x = FindRequestCommon{}
	mi := &file_sentinel_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequestCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequestCommon) ProtoMessage() {}

func (x *FindRequestCommon) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequestCommon.ProtoReflect.Descriptor instead.
func (*FindRequestCommon) Descriptor() ([]byte, []int) {
	return file_sentinel_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *FindRequestCommon) GetPage() uint32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *FindRequestCommon) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *FindRequestCommon) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *FindRequestCommon) GetIsAscOrder() bool {
	if x != nil {
		return x.IsAscOrder
	}
	return false
}

var File_sentinel_common_v1_common_proto protoreflect.FileDescriptor

const file_sentinel_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1fsentinel/common/v1/common.proto\x12\x12sentinel.common.v1\"\xb4\x01\n" +
	"\x11FindRequestCommon\x12\x17\n" +
	"\x04page\x18\x01 \x01(\rH\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x01R\bpageSize\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\x03 \x01(\tH\x02R\aorderBy\x88\x01\x01\x12 \n" +
	"\fis_asc_order\x18\x04 \x01(\bR\n" +
	"isAscOrderB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_sizeB\v\n" +
	"\t_order_byB\xe4\x01\n" +
	"\x16com.sentinel.common.v1B\vCommonProtoP\x01ZSgithub.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/common/v1;commonv1\xa2\x02\x03SCX\xaa\x02\x12Sentinel.Common.V1\xca\x02\x12Sentinel\\Common\\V1\xe2\x02\x1eSentinel\\Common\\V1\\GPBMetadata\xea\x02\x14Sentinel::Common::V1b\x06proto3"

var (
	file_sentinel_common_v1_common_proto_rawDescOnce sync.Once
	file_sentinel_common_v1_common_proto_rawDescData []byte
)

func file_sentinel_common_v1_common_proto_rawDescGZIP() []byte {
	file_sentinel_common_v1_common_proto_rawDescOnce.Do(func() {
		file_sentinel_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinel_common_v1_common_proto_rawDesc), len(file_sentinel_common_v1_common_proto_rawDesc)))
	})
	return file_sentinel_common_v1_common_proto_rawDescData
}

var file_sentinel_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sentinel_common_v1_common_proto_goTypes = []any{
	(*FindRequestCommon)(nil), // 0: sentinel.common.v1.FindRequestCommon
}
var file_sentinel_common_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sentinel_common_v1_common_proto_init() }
func file_sentinel_common_v1_common_proto_init() {
	if File_sentinel_common_v1_common_proto != nil {
		return
	}
	file_sentinel_common_v1_common_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinel_common_v1_common_proto_rawDesc), len(file_sentinel_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sentinel_common_v1_common_proto_goTypes,
		DependencyIndexes: file_sentinel_common_v1_common_proto_depIdxs,
		MessageInfos:      file_sentinel_common_v1_common_proto_msgTypes,
	}.Build()
	File_sentinel_common_v1_common_proto = out.File
	file_sentinel_common_v1_common_proto_goTypes = nil
	file_sentinel_common_v1_common_proto_depIdxs = nil
}
