// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_resource_agents

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

type Querier interface {
	CountByResourceID(ctx context.Context, resourceID string) (int64, error)
	Create(ctx context.Context, arg CreateParams) (*models.ResourceAgent, error)
	Delete(ctx context.Context, id string) error
	DeleteByResourceID(ctx context.Context, resourceID string) error
	DeleteByResourceIDAndAgentID(ctx context.Context, resourceID string, agentID string) error
	ExistsByResourceIDAndAgentID(ctx context.Context, resourceID string, agentID string) (int64, error)
	GetAll(ctx context.Context) ([]*models.ResourceAgent, error)
	GetAllByResourceID(ctx context.Context, resourceID string) ([]*models.ResourceAgent, error)
	GetByID(ctx context.Context, id string) (*models.ResourceAgent, error)
}

var _ Querier = (*Queries)(nil)
