// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.11
package repo_services

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameServices TableName = "services"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameServicesId                     ColumnName = "id"
	ColumnNameServicesName                   ColumnName = "name"
	ColumnNameServicesProtocol               ColumnName = "protocol"
	ColumnNameServicesInterval               ColumnName = "interval"
	ColumnNameServicesTimeout                ColumnName = "timeout"
	ColumnNameServicesRetries                ColumnName = "retries"
	ColumnNameServicesTags                   ColumnName = "tags"
	ColumnNameServicesConfig                 ColumnName = "config"
	ColumnNameServicesIsEnabled              ColumnName = "is_enabled"
	ColumnNameServicesIsNotificationsEnabled ColumnName = "is_notifications_enabled"
	ColumnNameServicesCreatedAt              ColumnName = "created_at"
	ColumnNameServicesUpdatedAt              ColumnName = "updated_at"
)

func ServicesColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameServicesId,
		ColumnNameServicesName,
		ColumnNameServicesProtocol,
		ColumnNameServicesInterval,
		ColumnNameServicesTimeout,
		ColumnNameServicesRetries,
		ColumnNameServicesTags,
		ColumnNameServicesConfig,
		ColumnNameServicesIsEnabled,
		ColumnNameServicesIsNotificationsEnabled,
		ColumnNameServicesCreatedAt,
		ColumnNameServicesUpdatedAt,
	}
}
