// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services_gen.sql

package repo_services

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
	"github.com/sxwebdev/sentinel/pkg/dbutils"
)

const create = `-- name: Create :one
INSERT INTO services (id, name, protocol, interval, timeout, retries, tags, config, is_enabled)
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	RETURNING id, name, protocol, interval, timeout, retries, json(tags), json(config), is_enabled, created_at, updated_at
`

type CreateParams struct {
	ID        string                     `db:"id" json:"id"`
	Name      string                     `db:"name" json:"name"`
	Protocol  models.ServiceProtocolType `db:"protocol" json:"protocol"`
	Interval  dbutils.Duration           `db:"interval" json:"interval"`
	Timeout   dbutils.Duration           `db:"timeout" json:"timeout"`
	Retries   int64                      `db:"retries" json:"retries"`
	Tags      dbutils.JSONField          `db:"tags" json:"tags"`
	Config    dbutils.JSONField          `db:"config" json:"config"`
	IsEnabled bool                       `db:"is_enabled" json:"is_enabled"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Service, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Name,
		arg.Protocol,
		arg.Interval,
		arg.Timeout,
		arg.Retries,
		arg.Tags,
		arg.Config,
		arg.IsEnabled,
	)
	var i models.Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Interval,
		&i.Timeout,
		&i.Retries,
		&i.Tags,
		&i.Config,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM services WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, name, protocol, interval, timeout, retries, json(tags), json(config), is_enabled, created_at, updated_at FROM services WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Service, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Interval,
		&i.Timeout,
		&i.Retries,
		&i.Tags,
		&i.Config,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
