// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: sentinel/resources/v1/service.proto

package resourcesv1

import (
	v1 "github.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceKind int32

const (
	ResourceKind_RESOURCE_KIND_UNSPECIFIED ResourceKind = 0
	ResourceKind_RESOURCE_KIND_SERVICE     ResourceKind = 1
	ResourceKind_RESOURCE_KIND_SERVER      ResourceKind = 2
)

// Enum value maps for ResourceKind.
var (
	ResourceKind_name = map[int32]string{
		0: "RESOURCE_KIND_UNSPECIFIED",
		1: "RESOURCE_KIND_SERVICE",
		2: "RESOURCE_KIND_SERVER",
	}
	ResourceKind_value = map[string]int32{
		"RESOURCE_KIND_UNSPECIFIED": 0,
		"RESOURCE_KIND_SERVICE":     1,
		"RESOURCE_KIND_SERVER":      2,
	}
)

func (x ResourceKind) Enum() *ResourceKind {
	p := new(ResourceKind)
	*p = x
	return p
}

func (x ResourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sentinel_resources_v1_service_proto_enumTypes[0].Descriptor()
}

func (ResourceKind) Type() protoreflect.EnumType {
	return &file_sentinel_resources_v1_service_proto_enumTypes[0]
}

func (x ResourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceKind.Descriptor instead.
func (ResourceKind) EnumDescriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{0}
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{0}
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Kind          ResourceKind           `protobuf:"varint,5,opt,name=kind,proto3,enum=sentinel.resources.v1.ResourceKind" json:"kind,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Payload       *Payload               `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Resource) GetKind() ResourceKind {
	if x != nil {
		return x.Kind
	}
	return ResourceKind_RESOURCE_KIND_UNSPECIFIED
}

func (x *Resource) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Resource) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Resource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Resource) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ResourcesList requests a list of resources.
type ResourcesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *v1.FindRequestCommon  `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesListRequest) Reset() {
	*x = ResourcesListRequest{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesListRequest) ProtoMessage() {}

func (x *ResourcesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesListRequest.ProtoReflect.Descriptor instead.
func (*ResourcesListRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ResourcesListRequest) GetCommon() *v1.FindRequestCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

type ResourcesListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Resource            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesListResponse) Reset() {
	*x = ResourcesListResponse{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesListResponse) ProtoMessage() {}

func (x *ResourcesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesListResponse.ProtoReflect.Descriptor instead.
func (*ResourcesListResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResourcesListResponse) GetItems() []*Resource {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ResourcesListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ResourceGet requests a resource by ID.
type ResourceGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceGetRequest) Reset() {
	*x = ResourceGetRequest{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGetRequest) ProtoMessage() {}

func (x *ResourceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGetRequest.ProtoReflect.Descriptor instead.
func (*ResourceGetRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResourceGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Resource              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceGetResponse) Reset() {
	*x = ResourceGetResponse{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGetResponse) ProtoMessage() {}

func (x *ResourceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGetResponse.ProtoReflect.Descriptor instead.
func (*ResourceGetResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceGetResponse) GetItem() *Resource {
	if x != nil {
		return x.Item
	}
	return nil
}

// ResourceCreate creates a new resource.
type ResourceCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AgentIds      []string               `protobuf:"bytes,2,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Kind          ResourceKind           `protobuf:"varint,5,opt,name=kind,proto3,enum=sentinel.resources.v1.ResourceKind" json:"kind,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Payload       *Payload               `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceCreateRequest) Reset() {
	*x = ResourceCreateRequest{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCreateRequest) ProtoMessage() {}

func (x *ResourceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCreateRequest.ProtoReflect.Descriptor instead.
func (*ResourceCreateRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceCreateRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ResourceCreateRequest) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *ResourceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResourceCreateRequest) GetKind() ResourceKind {
	if x != nil {
		return x.Kind
	}
	return ResourceKind_RESOURCE_KIND_UNSPECIFIED
}

func (x *ResourceCreateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ResourceCreateRequest) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ResourceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Resource              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceCreateResponse) Reset() {
	*x = ResourceCreateResponse{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCreateResponse) ProtoMessage() {}

func (x *ResourceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCreateResponse.ProtoReflect.Descriptor instead.
func (*ResourceCreateResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceCreateResponse) GetItem() *Resource {
	if x != nil {
		return x.Item
	}
	return nil
}

// ResourceUpdate updates an existing resource.
type ResourceUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Payload       *Payload               `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	AgentIds      []string               `protobuf:"bytes,6,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUpdateRequest) Reset() {
	*x = ResourceUpdateRequest{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUpdateRequest) ProtoMessage() {}

func (x *ResourceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ResourceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResourceUpdateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ResourceUpdateRequest) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ResourceUpdateRequest) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

type ResourceUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Resource              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUpdateResponse) Reset() {
	*x = ResourceUpdateResponse{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUpdateResponse) ProtoMessage() {}

func (x *ResourceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUpdateResponse.ProtoReflect.Descriptor instead.
func (*ResourceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceUpdateResponse) GetItem() *Resource {
	if x != nil {
		return x.Item
	}
	return nil
}

// ResourceDelete deletes a resource by ID.
type ResourceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDeleteRequest) Reset() {
	*x = ResourceDeleteRequest{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDeleteRequest) ProtoMessage() {}

func (x *ResourceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ResourceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *ResourceDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResourceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDeleteResponse) Reset() {
	*x = ResourceDeleteResponse{}
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDeleteResponse) ProtoMessage() {}

func (x *ResourceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_resources_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ResourceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_resources_v1_service_proto_rawDescGZIP(), []int{11}
}

var File_sentinel_resources_v1_service_proto protoreflect.FileDescriptor

const file_sentinel_resources_v1_service_proto_rawDesc = "" +
	"\n" +
	"#sentinel/resources/v1/service.proto\x12\x15sentinel.resources.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fsentinel/common/v1/common.proto\"\t\n" +
	"\aPayload\"\xec\x02\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x127\n" +
	"\x04kind\x18\x05 \x01(\x0e2#.sentinel.resources.v1.ResourceKindR\x04kind\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x128\n" +
	"\apayload\x18\a \x01(\v2\x1e.sentinel.resources.v1.PayloadR\apayload\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"U\n" +
	"\x14ResourcesListRequest\x12=\n" +
	"\x06common\x18\x01 \x01(\v2%.sentinel.common.v1.FindRequestCommonR\x06common\"d\n" +
	"\x15ResourcesListResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.sentinel.resources.v1.ResourceR\x05items\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"$\n" +
	"\x12ResourceGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x13ResourceGetResponse\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.sentinel.resources.v1.ResourceR\x04item\"\x90\x02\n" +
	"\x15ResourceCreateRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tagent_ids\x18\x02 \x03(\tR\bagentIds\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x127\n" +
	"\x04kind\x18\x05 \x01(\x0e2#.sentinel.resources.v1.ResourceKindR\x04kind\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x128\n" +
	"\apayload\x18\a \x01(\v2\x1e.sentinel.resources.v1.PayloadR\apayload\"M\n" +
	"\x16ResourceCreateResponse\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.sentinel.resources.v1.ResourceR\x04item\"\xc8\x01\n" +
	"\x15ResourceUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x128\n" +
	"\apayload\x18\x05 \x01(\v2\x1e.sentinel.resources.v1.PayloadR\apayload\x12\x1b\n" +
	"\tagent_ids\x18\x06 \x03(\tR\bagentIds\"M\n" +
	"\x16ResourceUpdateResponse\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.sentinel.resources.v1.ResourceR\x04item\"'\n" +
	"\x15ResourceDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16ResourceDeleteResponse*b\n" +
	"\fResourceKind\x12\x1d\n" +
	"\x19RESOURCE_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESOURCE_KIND_SERVICE\x10\x01\x12\x18\n" +
	"\x14RESOURCE_KIND_SERVER\x10\x022\xb1\x04\n" +
	"\x10ResourcesService\x12j\n" +
	"\rResourcesList\x12+.sentinel.resources.v1.ResourcesListRequest\x1a,.sentinel.resources.v1.ResourcesListResponse\x12d\n" +
	"\vResourceGet\x12).sentinel.resources.v1.ResourceGetRequest\x1a*.sentinel.resources.v1.ResourceGetResponse\x12m\n" +
	"\x0eResourceCreate\x12,.sentinel.resources.v1.ResourceCreateRequest\x1a-.sentinel.resources.v1.ResourceCreateResponse\x12m\n" +
	"\x0eResourceUpdate\x12,.sentinel.resources.v1.ResourceUpdateRequest\x1a-.sentinel.resources.v1.ResourceUpdateResponse\x12m\n" +
	"\x0eResourceDelete\x12,.sentinel.resources.v1.ResourceDeleteRequest\x1a-.sentinel.resources.v1.ResourceDeleteResponseB\xfa\x01\n" +
	"\x19com.sentinel.resources.v1B\fServiceProtoP\x01ZYgithub.com/sxwebdev/sentinel/internal/hub/hubserver/api/sentinel/resources/v1;resourcesv1\xa2\x02\x03SRX\xaa\x02\x15Sentinel.Resources.V1\xca\x02\x15Sentinel\\Resources\\V1\xe2\x02!Sentinel\\Resources\\V1\\GPBMetadata\xea\x02\x17Sentinel::Resources::V1b\x06proto3"

var (
	file_sentinel_resources_v1_service_proto_rawDescOnce sync.Once
	file_sentinel_resources_v1_service_proto_rawDescData []byte
)

func file_sentinel_resources_v1_service_proto_rawDescGZIP() []byte {
	file_sentinel_resources_v1_service_proto_rawDescOnce.Do(func() {
		file_sentinel_resources_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinel_resources_v1_service_proto_rawDesc), len(file_sentinel_resources_v1_service_proto_rawDesc)))
	})
	return file_sentinel_resources_v1_service_proto_rawDescData
}

var file_sentinel_resources_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sentinel_resources_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sentinel_resources_v1_service_proto_goTypes = []any{
	(ResourceKind)(0),              // 0: sentinel.resources.v1.ResourceKind
	(*Payload)(nil),                // 1: sentinel.resources.v1.Payload
	(*Resource)(nil),               // 2: sentinel.resources.v1.Resource
	(*ResourcesListRequest)(nil),   // 3: sentinel.resources.v1.ResourcesListRequest
	(*ResourcesListResponse)(nil),  // 4: sentinel.resources.v1.ResourcesListResponse
	(*ResourceGetRequest)(nil),     // 5: sentinel.resources.v1.ResourceGetRequest
	(*ResourceGetResponse)(nil),    // 6: sentinel.resources.v1.ResourceGetResponse
	(*ResourceCreateRequest)(nil),  // 7: sentinel.resources.v1.ResourceCreateRequest
	(*ResourceCreateResponse)(nil), // 8: sentinel.resources.v1.ResourceCreateResponse
	(*ResourceUpdateRequest)(nil),  // 9: sentinel.resources.v1.ResourceUpdateRequest
	(*ResourceUpdateResponse)(nil), // 10: sentinel.resources.v1.ResourceUpdateResponse
	(*ResourceDeleteRequest)(nil),  // 11: sentinel.resources.v1.ResourceDeleteRequest
	(*ResourceDeleteResponse)(nil), // 12: sentinel.resources.v1.ResourceDeleteResponse
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
	(*v1.FindRequestCommon)(nil),   // 14: sentinel.common.v1.FindRequestCommon
}
var file_sentinel_resources_v1_service_proto_depIdxs = []int32{
	0,  // 0: sentinel.resources.v1.Resource.kind:type_name -> sentinel.resources.v1.ResourceKind
	1,  // 1: sentinel.resources.v1.Resource.payload:type_name -> sentinel.resources.v1.Payload
	13, // 2: sentinel.resources.v1.Resource.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: sentinel.resources.v1.Resource.updated_at:type_name -> google.protobuf.Timestamp
	14, // 4: sentinel.resources.v1.ResourcesListRequest.common:type_name -> sentinel.common.v1.FindRequestCommon
	2,  // 5: sentinel.resources.v1.ResourcesListResponse.items:type_name -> sentinel.resources.v1.Resource
	2,  // 6: sentinel.resources.v1.ResourceGetResponse.item:type_name -> sentinel.resources.v1.Resource
	0,  // 7: sentinel.resources.v1.ResourceCreateRequest.kind:type_name -> sentinel.resources.v1.ResourceKind
	1,  // 8: sentinel.resources.v1.ResourceCreateRequest.payload:type_name -> sentinel.resources.v1.Payload
	2,  // 9: sentinel.resources.v1.ResourceCreateResponse.item:type_name -> sentinel.resources.v1.Resource
	1,  // 10: sentinel.resources.v1.ResourceUpdateRequest.payload:type_name -> sentinel.resources.v1.Payload
	2,  // 11: sentinel.resources.v1.ResourceUpdateResponse.item:type_name -> sentinel.resources.v1.Resource
	3,  // 12: sentinel.resources.v1.ResourcesService.ResourcesList:input_type -> sentinel.resources.v1.ResourcesListRequest
	5,  // 13: sentinel.resources.v1.ResourcesService.ResourceGet:input_type -> sentinel.resources.v1.ResourceGetRequest
	7,  // 14: sentinel.resources.v1.ResourcesService.ResourceCreate:input_type -> sentinel.resources.v1.ResourceCreateRequest
	9,  // 15: sentinel.resources.v1.ResourcesService.ResourceUpdate:input_type -> sentinel.resources.v1.ResourceUpdateRequest
	11, // 16: sentinel.resources.v1.ResourcesService.ResourceDelete:input_type -> sentinel.resources.v1.ResourceDeleteRequest
	4,  // 17: sentinel.resources.v1.ResourcesService.ResourcesList:output_type -> sentinel.resources.v1.ResourcesListResponse
	6,  // 18: sentinel.resources.v1.ResourcesService.ResourceGet:output_type -> sentinel.resources.v1.ResourceGetResponse
	8,  // 19: sentinel.resources.v1.ResourcesService.ResourceCreate:output_type -> sentinel.resources.v1.ResourceCreateResponse
	10, // 20: sentinel.resources.v1.ResourcesService.ResourceUpdate:output_type -> sentinel.resources.v1.ResourceUpdateResponse
	12, // 21: sentinel.resources.v1.ResourcesService.ResourceDelete:output_type -> sentinel.resources.v1.ResourceDeleteResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_sentinel_resources_v1_service_proto_init() }
func file_sentinel_resources_v1_service_proto_init() {
	if File_sentinel_resources_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinel_resources_v1_service_proto_rawDesc), len(file_sentinel_resources_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentinel_resources_v1_service_proto_goTypes,
		DependencyIndexes: file_sentinel_resources_v1_service_proto_depIdxs,
		EnumInfos:         file_sentinel_resources_v1_service_proto_enumTypes,
		MessageInfos:      file_sentinel_resources_v1_service_proto_msgTypes,
	}.Build()
	File_sentinel_resources_v1_service_proto = out.File
	file_sentinel_resources_v1_service_proto_goTypes = nil
	file_sentinel_resources_v1_service_proto_depIdxs = nil
}
