// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incident_states_gen.sql

package repo_incident_states

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

const create = `-- name: Create :one
INSERT INTO incident_states (id, incident_id, status, level)
	VALUES (?, ?, ?, ?)
	RETURNING id, incident_id, status, level, created_at, updated_at
`

type CreateParams struct {
	ID         string `db:"id" json:"id"`
	IncidentID string `db:"incident_id" json:"incident_id"`
	Status     string `db:"status" json:"status"`
	Level      int64  `db:"level" json:"level"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.IncidentState, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.IncidentID,
		arg.Status,
		arg.Level,
	)
	var i models.IncidentState
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM incident_states WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, incident_id, status, level, created_at, updated_at FROM incident_states
`

func (q *Queries) GetAll(ctx context.Context) ([]*models.IncidentState, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.IncidentState{}
	for rows.Next() {
		var i models.IncidentState
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, incident_id, status, level, created_at, updated_at FROM incident_states WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.IncidentState, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.IncidentState
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
