// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_incident_states

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.IncidentState, error)
	Delete(ctx context.Context, id string) error
	GetAll(ctx context.Context) ([]*models.IncidentState, error)
	GetByID(ctx context.Context, id string) (*models.IncidentState, error)
}

var _ Querier = (*Queries)(nil)
