// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: sentinel/common/v1/info.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AvailableUpdate represents information about an available update
type AvailableUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsAvailableManual bool                   `protobuf:"varint,1,opt,name=is_available_manual,json=isAvailableManual,proto3" json:"is_available_manual,omitempty"`
	TagName           string                 `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	Url               string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AvailableUpdate) Reset() {
	*x = AvailableUpdate{}
	mi := &file_sentinel_common_v1_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableUpdate) ProtoMessage() {}

func (x *AvailableUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_common_v1_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableUpdate.ProtoReflect.Descriptor instead.
func (*AvailableUpdate) Descriptor() ([]byte, []int) {
	return file_sentinel_common_v1_info_proto_rawDescGZIP(), []int{0}
}

func (x *AvailableUpdate) GetIsAvailableManual() bool {
	if x != nil {
		return x.IsAvailableManual
	}
	return false
}

func (x *AvailableUpdate) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *AvailableUpdate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AvailableUpdate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ServerInfo represents information about the server
type ServerInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CommitHash      string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	BuildDate       string                 `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	GoVersion       string                 `protobuf:"bytes,4,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	SqliteVersion   string                 `protobuf:"bytes,5,opt,name=sqlite_version,json=sqliteVersion,proto3" json:"sqlite_version,omitempty"`
	Os              string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Arch            string                 `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	AvailableUpdate *AvailableUpdate       `protobuf:"bytes,8,opt,name=available_update,json=availableUpdate,proto3,oneof" json:"available_update,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_sentinel_common_v1_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_common_v1_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_sentinel_common_v1_info_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *ServerInfo) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *ServerInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *ServerInfo) GetSqliteVersion() string {
	if x != nil {
		return x.SqliteVersion
	}
	return ""
}

func (x *ServerInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ServerInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *ServerInfo) GetAvailableUpdate() *AvailableUpdate {
	if x != nil {
		return x.AvailableUpdate
	}
	return nil
}

func (x *ServerInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

var File_sentinel_common_v1_info_proto protoreflect.FileDescriptor

const file_sentinel_common_v1_info_proto_rawDesc = "" +
	"\n" +
	"\x1dsentinel/common/v1/info.proto\x12\x12sentinel.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\x0fAvailableUpdate\x12.\n" +
	"\x13is_available_manual\x18\x01 \x01(\bR\x11isAvailableManual\x12\x19\n" +
	"\btag_name\x18\x02 \x01(\tR\atagName\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xf5\x02\n" +
	"\n" +
	"ServerInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\x12\x1d\n" +
	"\n" +
	"go_version\x18\x04 \x01(\tR\tgoVersion\x12%\n" +
	"\x0esqlite_version\x18\x05 \x01(\tR\rsqliteVersion\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch\x12S\n" +
	"\x10available_update\x18\b \x01(\v2#.sentinel.common.v1.AvailableUpdateH\x00R\x0favailableUpdate\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAtB\x13\n" +
	"\x11_available_updateB\xda\x01\n" +
	"\x16com.sentinel.common.v1B\tInfoProtoP\x01ZKgithub.com/sxwebdev/sentinel/internal/agent/api/sentinel/common/v1;commonv1\xa2\x02\x03SCX\xaa\x02\x12Sentinel.Common.V1\xca\x02\x12Sentinel\\Common\\V1\xe2\x02\x1eSentinel\\Common\\V1\\GPBMetadata\xea\x02\x14Sentinel::Common::V1b\x06proto3"

var (
	file_sentinel_common_v1_info_proto_rawDescOnce sync.Once
	file_sentinel_common_v1_info_proto_rawDescData []byte
)

func file_sentinel_common_v1_info_proto_rawDescGZIP() []byte {
	file_sentinel_common_v1_info_proto_rawDescOnce.Do(func() {
		file_sentinel_common_v1_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinel_common_v1_info_proto_rawDesc), len(file_sentinel_common_v1_info_proto_rawDesc)))
	})
	return file_sentinel_common_v1_info_proto_rawDescData
}

var file_sentinel_common_v1_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sentinel_common_v1_info_proto_goTypes = []any{
	(*AvailableUpdate)(nil),       // 0: sentinel.common.v1.AvailableUpdate
	(*ServerInfo)(nil),            // 1: sentinel.common.v1.ServerInfo
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_sentinel_common_v1_info_proto_depIdxs = []int32{
	0, // 0: sentinel.common.v1.ServerInfo.available_update:type_name -> sentinel.common.v1.AvailableUpdate
	2, // 1: sentinel.common.v1.ServerInfo.started_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sentinel_common_v1_info_proto_init() }
func file_sentinel_common_v1_info_proto_init() {
	if File_sentinel_common_v1_info_proto != nil {
		return
	}
	file_sentinel_common_v1_info_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinel_common_v1_info_proto_rawDesc), len(file_sentinel_common_v1_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sentinel_common_v1_info_proto_goTypes,
		DependencyIndexes: file_sentinel_common_v1_info_proto_depIdxs,
		MessageInfos:      file_sentinel_common_v1_info_proto_msgTypes,
	}.Build()
	File_sentinel_common_v1_info_proto = out.File
	file_sentinel_common_v1_info_proto_goTypes = nil
	file_sentinel_common_v1_info_proto_depIdxs = nil
}
