// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.12
package repo_monitor_checks

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameMonitorChecks TableName = "monitor_checks"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameMonitorChecksId           ColumnName = "id"
	ColumnNameMonitorChecksProjectId    ColumnName = "project_id"
	ColumnNameMonitorChecksMonitorId    ColumnName = "monitor_id"
	ColumnNameMonitorChecksRevisionId   ColumnName = "revision_id"
	ColumnNameMonitorChecksResourceId   ColumnName = "resource_id"
	ColumnNameMonitorChecksAgentId      ColumnName = "agent_id"
	ColumnNameMonitorChecksStartedAt    ColumnName = "started_at"
	ColumnNameMonitorChecksCompletedAt  ColumnName = "completed_at"
	ColumnNameMonitorChecksSeverity     ColumnName = "severity"
	ColumnNameMonitorChecksResponseTime ColumnName = "response_time"
	ColumnNameMonitorChecksEvaluation   ColumnName = "evaluation"
	ColumnNameMonitorChecksMeta         ColumnName = "meta"
	ColumnNameMonitorChecksCreatedAt    ColumnName = "created_at"
)

func MonitorChecksColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameMonitorChecksId,
		ColumnNameMonitorChecksProjectId,
		ColumnNameMonitorChecksMonitorId,
		ColumnNameMonitorChecksRevisionId,
		ColumnNameMonitorChecksResourceId,
		ColumnNameMonitorChecksAgentId,
		ColumnNameMonitorChecksStartedAt,
		ColumnNameMonitorChecksCompletedAt,
		ColumnNameMonitorChecksSeverity,
		ColumnNameMonitorChecksResponseTime,
		ColumnNameMonitorChecksEvaluation,
		ColumnNameMonitorChecksMeta,
		ColumnNameMonitorChecksCreatedAt,
	}
}
