// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor_checks_gen.sql

package repo_monitor_checks

import (
	"context"
	"time"

	"github.com/sxwebdev/sentinel/internal/models"
	"github.com/sxwebdev/sentinel/internal/store/storecmn"
)

const create = `-- name: Create :one
INSERT INTO monitor_checks (id, project_id, monitor_id, revision_id, resource_id, agent_id, started_at, completed_at, severity, response_time, evaluation, meta)
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	RETURNING id, project_id, monitor_id, revision_id, resource_id, agent_id, started_at, completed_at, severity, response_time, evaluation, meta, created_at
`

type CreateParams struct {
	ID           string             `db:"id" json:"id"`
	ProjectID    string             `db:"project_id" json:"project_id"`
	MonitorID    string             `db:"monitor_id" json:"monitor_id"`
	RevisionID   int64              `db:"revision_id" json:"revision_id"`
	ResourceID   string             `db:"resource_id" json:"resource_id"`
	AgentID      string             `db:"agent_id" json:"agent_id"`
	StartedAt    time.Time          `db:"started_at" json:"started_at"`
	CompletedAt  time.Time          `db:"completed_at" json:"completed_at"`
	Severity     int64              `db:"severity" json:"severity"`
	ResponseTime int64              `db:"response_time" json:"response_time"`
	Evaluation   storecmn.JSONField `db:"evaluation" json:"evaluation"`
	Meta         storecmn.JSONField `db:"meta" json:"meta"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.MonitorCheck, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.ProjectID,
		arg.MonitorID,
		arg.RevisionID,
		arg.ResourceID,
		arg.AgentID,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Severity,
		arg.ResponseTime,
		arg.Evaluation,
		arg.Meta,
	)
	var i models.MonitorCheck
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MonitorID,
		&i.RevisionID,
		&i.ResourceID,
		&i.AgentID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Severity,
		&i.ResponseTime,
		&i.Evaluation,
		&i.Meta,
		&i.CreatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM monitor_checks WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, project_id, monitor_id, revision_id, resource_id, agent_id, started_at, completed_at, severity, response_time, evaluation, meta, created_at FROM monitor_checks
`

func (q *Queries) GetAll(ctx context.Context) ([]*models.MonitorCheck, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.MonitorCheck{}
	for rows.Next() {
		var i models.MonitorCheck
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MonitorID,
			&i.RevisionID,
			&i.ResourceID,
			&i.AgentID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Severity,
			&i.ResponseTime,
			&i.Evaluation,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, project_id, monitor_id, revision_id, resource_id, agent_id, started_at, completed_at, severity, response_time, evaluation, meta, created_at FROM monitor_checks WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.MonitorCheck, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.MonitorCheck
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MonitorID,
		&i.RevisionID,
		&i.ResourceID,
		&i.AgentID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Severity,
		&i.ResponseTime,
		&i.Evaluation,
		&i.Meta,
		&i.CreatedAt,
	)
	return &i, err
}
