// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.12
package repo_monitors

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameMonitors TableName = "monitors"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameMonitorsId         ColumnName = "id"
	ColumnNameMonitorsProjectId  ColumnName = "project_id"
	ColumnNameMonitorsResourceId ColumnName = "resource_id"
	ColumnNameMonitorsName       ColumnName = "name"
	ColumnNameMonitorsKind       ColumnName = "kind"
	ColumnNameMonitorsIsEnabled  ColumnName = "is_enabled"
	ColumnNameMonitorsTags       ColumnName = "tags"
	ColumnNameMonitorsCreatedAt  ColumnName = "created_at"
	ColumnNameMonitorsUpdatedAt  ColumnName = "updated_at"
)

func MonitorsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameMonitorsId,
		ColumnNameMonitorsProjectId,
		ColumnNameMonitorsResourceId,
		ColumnNameMonitorsName,
		ColumnNameMonitorsKind,
		ColumnNameMonitorsIsEnabled,
		ColumnNameMonitorsTags,
		ColumnNameMonitorsCreatedAt,
		ColumnNameMonitorsUpdatedAt,
	}
}
