// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors_gen.sql

package repo_monitors

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
	"github.com/sxwebdev/sentinel/internal/store/storecmn"
)

const create = `-- name: Create :one
INSERT INTO monitors (id, project_id, resource_id, name, kind, is_enabled, tags)
	VALUES (?, ?, ?, ?, ?, ?, ?)
	RETURNING id, project_id, resource_id, name, kind, is_enabled, tags, created_at, updated_at
`

type CreateParams struct {
	ID         string             `db:"id" json:"id"`
	ProjectID  string             `db:"project_id" json:"project_id"`
	ResourceID string             `db:"resource_id" json:"resource_id"`
	Name       string             `db:"name" json:"name"`
	Kind       string             `db:"kind" json:"kind"`
	IsEnabled  bool               `db:"is_enabled" json:"is_enabled"`
	Tags       storecmn.JSONField `db:"tags" json:"tags"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Monitor, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.ProjectID,
		arg.ResourceID,
		arg.Name,
		arg.Kind,
		arg.IsEnabled,
		arg.Tags,
	)
	var i models.Monitor
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceID,
		&i.Name,
		&i.Kind,
		&i.IsEnabled,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM monitors WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, project_id, resource_id, name, kind, is_enabled, tags, created_at, updated_at FROM monitors
`

func (q *Queries) GetAll(ctx context.Context) ([]*models.Monitor, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Monitor{}
	for rows.Next() {
		var i models.Monitor
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ResourceID,
			&i.Name,
			&i.Kind,
			&i.IsEnabled,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, project_id, resource_id, name, kind, is_enabled, tags, created_at, updated_at FROM monitors WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Monitor, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Monitor
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceID,
		&i.Name,
		&i.Kind,
		&i.IsEnabled,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
