// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_monitors

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Monitor, error)
	Delete(ctx context.Context, id string) error
	Exist(ctx context.Context, id string) (int64, error)
	GetAll(ctx context.Context) ([]*models.Monitor, error)
	GetAllMonitorsByAgentID(ctx context.Context, id string) ([]*GetAllMonitorsByAgentIDRow, error)
	GetByID(ctx context.Context, id string) (*models.Monitor, error)
}

var _ Querier = (*Queries)(nil)
