// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.12
package repo_incident_events

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameIncidentEvents TableName = "incident_events"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameIncidentEventsId         ColumnName = "id"
	ColumnNameIncidentEventsIncidentId ColumnName = "incident_id"
	ColumnNameIncidentEventsCreatedAt  ColumnName = "created_at"
	ColumnNameIncidentEventsType       ColumnName = "type"
	ColumnNameIncidentEventsPayload    ColumnName = "payload"
)

func IncidentEventsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameIncidentEventsId,
		ColumnNameIncidentEventsIncidentId,
		ColumnNameIncidentEventsCreatedAt,
		ColumnNameIncidentEventsType,
		ColumnNameIncidentEventsPayload,
	}
}
