// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_incident_events

import (
	"context"

	"github.com/sxwebdev/sentinel/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.IncidentEvent, error)
	Delete(ctx context.Context, id int64) error
	GetAll(ctx context.Context) ([]*models.IncidentEvent, error)
	GetByID(ctx context.Context, id int64) (*models.IncidentEvent, error)
}

var _ Querier = (*Queries)(nil)
